### ISSUE TITLE
[Bug]: double 'double-quotes' in the saved *model*.html file

### ISSUE THREAD

**Issue by hakaserver** [BlafKing/sd-civitai-browser-plus#118]
### Describe the bug.

I'm not very knowledgeable of CSS and html, but from what I speculate, the html file created when using the 'save images' function is supposed to be used by the extension when loading the local models for display when using the 'Load all installed models', and that is probably why the page looks broken when opening the html file directly.
However I find very practical to just open these files in a browser to quickly check prompt information or the original model URL. Despite the formatting not exactly working when directly viewing the file in a browser, the sample images aren't loaded at all, since the .html file is created with double 'double-quotes' in the `<img>` tag:

```
 <img  data-sampleimg="true" src=""sample_0.png"">
```

### Steps to reproduce the problem.

1. Download sample images with "save images" button
2. Manually open the created .html file in a browser
3. The images are not loaded

### Expected behavior

When fixing the double quotes the images are loaded when directly viewing the .html file in a browser. Not sure if this breaks when viewing inside gradio through the extension, if that is really the supposed intention of the file as I imagine.

### System info

* Extension version: [6fd4c8c]
* OS: Win11
* SD-WebUI version: 1.6.0
* Python: 3.10.8

### Console logs

```Shell
---
```

**Comment by BlafKing** [comment]
This issue is now fixed in v3.0 :)
