### ISSUE TITLE
[Bug]: Model Preview Update Overwrites all Models Despite Unchecking the "Overwrite" Box

### ISSUE THREAD

**Issue by SchofieldPriest** [BlafKing/sd-civitai-browser-plus#123]
### Describe the bug.

In the "Update Models" portion, after unchecking the "Overwrite any existing previews, tags or descriptions." box and selecting the "Scan for Lora" option, CivitAI+ will still proceed to update the preview images of all of my Loras rather than only the ones that don't have a model preview. This leads to redundant downloads and a lot of extra time by the program spent doing so.

### Steps to reproduce the problem.

1. Go to Update Models
2. Check LORA, then uncheck "Overwrite any existing previews, tags or descriptions."
3. Press "Update Model Previews"
4. After sending all API requests, the extension will proceed to download a new preview for every model, rather than just the ones that have no preview.

### Expected behavior

After sending all API requests, the extension should only download previews for models that don't currently have one.

### System info

* Extension version: 3.0
* OS: Windows 10
* SD-WebUI version: 1.5
* Python: 3.10

### Console logs

```Shell
cmd log continues as normal, but saves a preview image for every model
```

**Comment by BlafKing** [comment]
Thanks for let me know!

This was caused by a silly oversight, I've made a quick hotfix for it that should fix the issue! :)

**Comment by SchofieldPriest** [comment]
Thank you @BlafKing ! How can I install this hotfix? I reinstalled the extension, but it doesn't seem like the fix was implemented that way.
