### ISSUE TITLE
[Bug]: Browsing images with video previous uses lots of CPU

### ISSUE THREAD

**Issue by sam42contact** [BlafKing/sd-civitai-browser-plus#124]
### Describe the bug.

This is a bug on civitai. Their video previews are buggy and make firefox decoder struggle with them.
A small fix is to simply remove autoplay and loop from civitai_api.py.

### Steps to reproduce the problem.

1. Search for models having a video preview
2. Check cpu usage (on firefox)

### Expected behavior

We expect to have low cpu usage

### System info

* Extension version: Latest
* OS: Linux
* SD-WebUI version: Irrelevant
* Python: Irrelevant

### Console logs

```Shell
Irrelevant
```

**Comment by BlafKing** [comment]
Thanks for reporting!
I'll add a toggle in the settings that you can use to disable `autoplay` and `loop` in the HTML creation in the next version :)

**Comment by BlafKing** [comment]
There is now a toggle in the settings that you can use to toggle the autoplay and loop entries to prevent auto playback of video's/gif's :)

**Comment by sam42contact** [comment]
Thank you <3
Nice work ;)
