### ISSUE TITLE
[Bug]: New base model "SDXL Turbo" needs to be added

### ISSUE THREAD

**Issue by ManOrMonster** [BlafKing/sd-civitai-browser-plus#126]
### Describe the bug.

A new base model "SDXL Turbo" has been added on Civitai. See [TurboVisionXL](https://civitai.com/models/215418/turbovisionxl-super-fast-xl-based-on-new-sdxl-turbo-3-5-step-quality-output-at-high-resolutions) as an example. This model does not appear in Civitai Browser+ searches.

### Steps to reproduce the problem.

Search for "turbovision".

### Expected behavior

Find TurboVision.

### System info

* Extension version:
* OS:
* SD-WebUI version:
* Python:

### Console logs

```Shell
N/A
```

**Comment by BlafKing** [comment]
Thanks for reporting!
I'm currently working on the next update which will include all the updated/new base models versions! :)
Updated/new base models: `SD 1.5 LCM, SDXL 1.0 LCM, SDXL Distilled, SDXL Turbo, SVD, SVD XT`

**Comment by BlafKing** [comment]
This has now been fixed/added in v3.1.0 :)
