### ISSUE TITLE
[Bug]: Save Images downloading files to the wrong location

### ISSUE THREAD

**Issue by hakaserver** [BlafKing/sd-civitai-browser-plus#129]
### Describe the bug.

When using the Save Images function with a custom save images location set, it downloads the files to the root of the drive, in the selected subfolder.

### Steps to reproduce the problem.

1. Set the custom save image location to `H:\SDWebui\stable-diffusion-webui\models_db`
2. Enable the new option "Use sub folders inside custom images location (Will append any content type and sub folders to the custom path.)"
3. Save settings
4. Open any Lycoris model page in the Civitai Browser+ tab.
5. Select subfolder "Styles"
6. Press Save Images
7. Files are downloaded to `H:\Styles` instead of `H:\SDWebui\stable-diffusion-webui\models_db\Lycoris\Styles`

### Expected behavior

In the case presented, it would be expected for the files to be downloaded at `H:\SDWebui\stable-diffusion-webui\models_db\Lycoris\Styles`

### System info

* Extension version: [3ead634](https://github.com/BlafKing/sd-civitai-browser-plus/commit/3ead634e1d81fa586e58de2ec06b417e17887721)
* OS: Win11
* SD-WebUI version: 1.6.0
* Python: 3.10.6

### Console logs

```Shell
CivitAI Browser+: Downloaded image 1
CivitAI Browser+: Downloaded image 2
CivitAI Browser+: Downloaded image 3
CivitAI Browser+: Downloaded image 4
CivitAI Browser+: Downloaded image 5
CivitAI Browser+: Downloaded image 6
CivitAI Browser+: Downloaded image 7
CivitAI Browser+: Downloaded image 8
```

**Comment by BlafKing** [comment]
Thanks for reporting!
That's odd, sounds like it's not receiving the folder path from the settings.

I experienced something similar during bug testing, and I think re-inserting the custom path helper for me, to verify, could you try the following?

Empty out the custom image path, then click the save settings button.
Re-insert the custom image path, then click the save settings button again and try to download some images.

**Comment by hakaserver** [comment]
> Thanks for reporting! That's odd, sounds like it's not receiving the folder path from the settings.
> 
> I experienced something similar during bug testing, and I think re-inserting the custom path helped for me, to verify, could you try the following?
> 
> Empty out the custom image path, then click the save settings button. Re-insert the custom image path, then click the save settings button again and try to download some images.

Already tried that, even restarting the webui in between changes or manuallu inputing the path in the config.json file. The result is always the same: if the path is empty it downloads the files in the normal download path, if there is a path set it downloads to the root folder of the drive.

**Comment by hakaserver** [comment]
I tried debugging and apparently it is failing to append the subfolder. Running the following in the custom code script:

```
import os
import scripts.civitai_api as _api
import scripts.civitai_global as gl
from modules.shared import cmd_opts, opts
image_location = getattr(opts, "image_location", r"")
desc = gl.json_info['description']
content_type = gl.json_info['type']
install_path = os.path.join(_api.contenttype_folder(content_type, desc, custom_folder=image_location))
print(install_path)
```
Returns the correct path `H:\SDWebui\stable-diffusion-webui\models_db\Lora`.
When testing the Save Images function without selecting a subfolder it correctly downloads to the path above.
I don't know how the gradio side of the code works, so I didn't know how to test that part, but I think it is failing to get the correct value for the 'sub_folder' variable.

**Comment by BlafKing** [comment]
Thanks for doing the debugging and publishing a fix for it!

Merged your request so I'll close this issue now :)
