### ISSUE TITLE
[Bug]: Update Models - Load installed models: error

### ISSUE THREAD

**Issue by schoenid** [BlafKing/sd-civitai-browser-plus#135]
### Describe the bug.

Trying to load my installed model to the browser leads to errors
![image_2023-12-13_222241857](https://github.com/BlafKing/sd-civitai-browser-plus/assets/15383666/67a4d45e-a80e-4798-a375-4dc9c81d4354)

### Steps to reproduce the problem.

1. Go to .... Civitai Browser - Update Models
2. Check ... Checkpoint
3. Press ... Load all installed models
![image_2023-12-13_222139994](https://github.com/BlafKing/sd-civitai-browser-plus/assets/15383666/292b3d70-90af-483d-9b3b-dde3ff2d6383)

### Expected behavior

Instead of an error message a button should appear, to "Load installed models to browser" or similar.

### System info

* Extension version: 035326f2 - 2023-12-09 17:24:35
* OS: Ubuntu Studio 22.04
* SD-WebUI version: version: v1.6.0
* Python: 3.10.12

### Console logs

```Shell
CivitAI Browser+: An error occurred for /home/sd/Games/stable-diffusion-webui/models/Stable-diffusion/SD Realistic Vision inpainting.safetensors: Expecting value: line 1 column 1 (char 0)
CivitAI Browser+: An error occurred for /home/sd/Games/stable-diffusion-webui/models/Stable-diffusion/SD Realistic Vision.safetensors: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/sd/Games/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/sd/Games/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/home/sd/Games/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/sd/Games/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/sd/Games/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/sd/Games/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/sd/Games/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/home/sd/Games/stable-diffusion-webui/extensions/sd-civitai-browser-plus/scripts/civitai_file_manage.py", line 791, in file_scan
    gl.ver_json = json.loads(response.text)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### Additional information

I've renamed all downloaded models, to have a better overview.
Until the last update, it was no problem for the sd-civitai-browser-plus extension.

**Comment by Worldgate** [comment]
Yea had problems myself with renamed files so now i just put them in renamed directories.

**Comment by schoenid** [comment]
In the meantime the extension works again.

The main reason was: the Civitai server was down or not reachable by some reason.
Altough, there should be an error message, which tells me, that **the server is down**, like on the browser page of the extension. 

However, the problem with the checkpoint model Realistic Vision (https://civitai.com/models/4201) has been with version V5.1 and  V5.1-inpainting, which did have wrong hash numbers in the json file (00445494c8 instead of ef76aa2332 for V5.1). I did install it by an earlier version of the same extension, so I don't know, how this is possible.
I've reloaded it (delete and install), renamed it and now everything is fine.

**Comment by BlafKing** [comment]
Good to know, thanks for reporting!

I've included an error message for when CivitAI is offline in the main browser, but I forgot to do so for the options in the update tab. I'll make sure to include that in a future update! :)

As for the wrong hash file, an earlier version used to assign models with the wrong SHA256 hash, which has been fixed in later versions, so that's probably where that issue originated from 😅

On rare occassions the hash is wrong on CivitAI's end, but that doesn't seem to be the case with this model.

**Comment by schoenid** [comment]
@BlafKing 

> I've included an error message for when CivitAI is offline in the main browser, but I forgot to do so for the options in the update tab. I'll make sure to include that in a future update! :)

Just thank you !!!

> Also make sure that when you rename a model, to also rename the matching .json file of the model, since the code expects those to have the same file name :)

Yeah. I rename always 2 or 3 files, depending on whether I want to use to original preview or my own ...
