### ISSUE TITLE
[Bug]: Lora+PT issue 

### ISSUE THREAD

**Issue by Les-Tin** [BlafKing/sd-civitai-browser-plus#138]
### Describe the bug.

There are lora+pt models on Civitai. When you select such models, 2 files are specified, if you download one of them, the second one can't be downloaded anymore.

### Steps to reproduce the problem.

1. Find the model Lora+PT using Civitai Browser (example: https://civitai.com/models/125775?modelVersionId=162226).
2. Try to download both files version 1.4
3. Only one of the files is downloaded. When trying to download the second file, Civitai browser+ tries to download it, but in the end the download button remains active, but the file itself is not downloaded.

### Expected behavior

Both models can be downloaded or they are downloaded at the same time

### System info

Extension version: b4590855
OS: Windows 10
SD-WebUI version: v1.7.0-132-g3d9a0d9e
Python: 3.11.6

### Console logs

```Shell
None
```

**Comment by BlafKing** [comment]
Thanks for reporting!

However, I can't seem to replicate this behavior with the model you mentioned.
It's true that whilst downloading you cannot select another file type of the same version, but after the model has completed downloading, then it should be possible to select the other file type and download that one as well as shown here:

https://github.com/BlafKing/sd-civitai-browser-plus/assets/9644716/e7df0b78-ae7f-4e02-acdb-9f51782c2bfb

![image](https://github.com/BlafKing/sd-civitai-browser-plus/assets/9644716/fbccc35a-2e8c-4f15-bd48-28e3e7b97a99)

I unfortunately don't have much to go off if you're not getting any errors in the log, a small fault that I noticed is that the button remains on "Download model" like you mentioned, but the file did successfully download, and after re-selecting the file, it does show up as "Delete".

Is this maybe what you were experiencing?

**Comment by Les-Tin** [comment]
Thanks for the reply. Yes, I may have overlooked the problem you mentioned and the fact that the file was downloaded. However, the download of the ".pt" file should be in the "embeddings" folder, shouldn't it? Otherwise, that embedding simply won't show up in the Lora selection interface.

**Comment by BlafKing** [comment]
I actually don't use SD-WebUI much myself, I enjoy making the extension a lot more than actually using SD-WebUI 😅 
I didn't know that that's where any .pt files should be placed, is this always the case for all .pt files?
If so I'll definately make sure to make the extension place those in the embeddings directory in a future update!

**Comment by Les-Tin** [comment]
Unfortunately, I think this rule cannot be applied in all cases. Many old Loras were in PickleTensors format, although nowadays Safetensors are everywhere and pt Loras are exotic, I think it's still worth considering. I don't know how it would work best, but I'll at least try to suggest it. 

If the opened card in the Civitai Browser belongs to the Lora category and contains two files, pt and safetensors, the pt file should be downloaded into the embeddings folder. 

It's just a silly suggestion, I don't know how things should work under the hood :)

**Comment by Les-Tin** [comment]
Yeah, the pt file should only be placed in the embeddings directory if it is accompanied by a Safetensors file, but if the Lora card contains only the pt file, it should go to the Lora directory. This workaround is not very clean, but since Civitai doesn't provide a native way to detect LoRA+pt combos, but it's the only possible way I can think of. 

Also, it might be useful to check the size of the pt file. Pt embeddings are quite small (<100kb) and this is a reliable sign that the file is not Lora.

**Comment by BlafKing** [comment]
Thanks for all the info!
The functionality you mentioned is now implemented in ([v3.1.0](https://github.com/BlafKing/sd-civitai-browser-plus/commit/d21758863a0605f5139b1f5f49af0a4e00880b02)) so I'll close this issue.

The issue where the download button remains displaying "Download" after you have finished downloading the second file still seems to occur, but please be assured that it should not actually cause any problems and I'll make sure to find a fix for it in another update :)

I'll go ahead and close this issue now, since it should be resolved!
