### ISSUE TITLE
Option to choose over multiple model download options

### ISSUE THREAD

**Issue by CesarCruzUtec** [BlafKing/sd-civitai-browser-plus#14]
**Is your feature request related to a problem? Please describe.**
When downloading models that have pruned and full versions, the extension downloads a random one i think, sometimes resulting in the full one.

**Describe the solution you'd like**
I would like an additional dropdown if there exist differente model options

**Additional context**
![image](https://github.com/BlafKing/sd-civitai-browser-plus/assets/67798431/ec49a288-690f-4816-9399-55b46d6593d3)
![image](https://github.com/BlafKing/sd-civitai-browser-plus/assets/67798431/78bb1382-68b1-48fb-8c96-eb16a22e0199)

**Comment by BlafKing** [comment]
Solid request!
I've just checked the API request return data and it looks like the individual files are present for each version and it does currently just take the first file in the list. I'll start working on attempting to implement an extra dropdown if there are multiple files per version!

**Comment by BlafKing** [comment]
I've published a new version (v1.8) which now includes an extra droplist where you can select the specific file you want to download.

You will still be able to download one file per version but you'll now be able to select which file that is.
The underlying code relies on expecting one file per version and almost all models have the same file names for each individual file so it's usually not possible to store both a pruned and full model of the same version anyway.

Was quite some work to implement this but it should all work well now! :)
