### ISSUE TITLE
[Bug]: Updating models (everything) generates an error

### ISSUE THREAD

**Issue by Rojinski** [BlafKing/sd-civitai-browser-plus#145]
### Describe the bug.

Hello,

Since two or three days, It became impossible to use the update tab in the extension: updating tags and infos, previews or models you arlready have. Everything was perfect untl then and I love your extension! So easy when you're like me keeping tons of models...

### Steps to reproduce the problem.

1. Go to Civitai Brower Plus tab
2. Choose "Update Models" tab
3. Check "checkpoint" or "Lora" or "TextualInversion" or "HyperNetworks"
4. Click on "Updates Scan" or "Update models infos and tags" or "Update Model Preview"
5. you get an "error"

It seems there are pbs to check updates for more than 100 models now... and also with Civitai API.  Same problem with SDNext (Vlad), so it's not a question of A1111 new version.  I've tried to disable ARIA2 in settings. Same issue. I've tried to enter my own civitai API key in settings, same stuff.

![Screenshot 2023-12-21 at 17-26-27 Stable Diffusion](https://github.com/BlafKing/sd-civitai-browser-plus/assets/122015375/2f4f5f84-d196-4866-b27c-7537910c0a35)

### Expected behavior

Two days ago, it was perfect for every task this fab extension is made for!! So it could be from Civitai... I have only 5 hypernetwork models and i have the same issue. when i try to update them. But yes, i have tons of checkpoints, LORA and TextualInversion... 

### System info

* Extension version: [b4590855](https://github.com/BlafKing/sd-civitai-browser-plus/commit/b45908554dda37c1467e095bc3d2033f52c66e36)
* OS: Windows 11
* SD-WebUI version: 1.7.0
* Python: 3.10.10

### Console logs

```Shell
Already up to date.
venv "D:\Programmes 2\Logiciels\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
Version: v1.7.0
Commit hash: cf2772fab0af5573da775e7437e6acdca424f26e
ReActor preheating... Device: CUDA
Launching Web UI with arguments: --xformers --medvram --no-half-vae
Additional Network extension not installed, Only hijack built-in lora
LoCon Extension hijack built-in lora successfully
[-] ADetailer initialized. version: 23.11.1, num models: 20
CivitAI Browser+: Aria2 RPC started

12/21 17:22:30 [NOTICE] IPv4 RPC: listening on TCP port 24000

12/21 17:22:30 [NOTICE] IPv6 RPC: listening on TCP port 24000
ControlNet preprocessor location: D:\Programmes 2\Logiciels\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-12-21 17:22:30,911 - ControlNet - INFO - ControlNet v1.1.423
2023-12-21 17:22:30,993 - ControlNet - INFO - ControlNet v1.1.423
17:22:31 - ReActor - STATUS - Running v0.6.0-a4
Loading weights [0724518c6b] from D:\Programmes 2\Logiciels\stable-diffusion-webui\models\Stable-diffusion\SDXL\juggernautXL_v7Rundiffusion.safetensors
Creating model from config: D:\Programmes 2\Logiciels\stable-diffusion-webui\repositories\generative-models\configs\inference\sd_xl_base.yaml
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 14.5s (prepare environment: 4.0s, import torch: 2.5s, import gradio: 0.7s, setup paths: 0.6s, initialize shared: 0.2s, other imports: 0.5s, setup gfpgan: 0.1s, list SD models: 0.3s, load scripts: 2.5s, create ui: 2.7s, gradio launch: 0.3s).
Loading VAE weights specified in settings: D:\Programmes 2\Logiciels\stable-diffusion-webui\models\VAE\sdxl_vae.safetensors
Applying attention optimization: xformers... done.
Model loaded in 7.1s (load weights from disk: 1.4s, create model: 0.7s, apply weights to model: 2.9s, load VAE: 0.1s, load textual inversion embeddings: 0.3s, calculate empty prompt: 1.6s).
Error: Received status code 503 with URL: https://civitai.com/api/v1/models?limit=100&ids=112229&ids=215538&ids=25573&ids=25694&ids=67192&ids=112013&ids=93529&ids=218300&ids=22922&ids=143386&ids=123307&ids=133005&ids=54073&ids=123697&ids=15003&ids=22402&ids=82972&ids=124674&ids=147720&ids=200061&ids=129666&ids=120127&ids=148871&ids=132840&ids=52548&ids=175959&ids=153425&ids=122608&ids=63920&ids=177777&ids=84728&ids=125703&ids=14722&ids=218483&ids=120964&ids=112902&ids=101055&ids=50000&ids=194768&ids=227059&ids=112769&ids=232370&ids=137890&ids=141592&ids=69587&ids=61086&ids=127923&ids=117263&ids=102080&ids=229392&ids=156522&ids=86789&ids=7371&ids=5273&ids=167318&ids=4814&ids=5952&ids=134760&ids=9114&ids=93249&ids=128453&ids=49216&ids=132632&ids=120841&ids=9052&ids=118114&ids=189109&ids=181107&ids=16325&ids=8392&ids=110426&ids=22975&ids=142320&ids=12334&ids=46049&ids=102001&ids=128607&ids=139489&ids=160505&ids=236274&ids=119229&ids=54009&ids=151568&ids=171067&ids=213093&ids=10540&ids=128226&ids=122822&ids=206917&ids=18208&ids=81458&ids=161068&ids=199656&ids=87371&ids=120741&ids=162052&ids=149359&ids=169868&ids=138331&ids=21916&ids=85492&ids=1540&ids=78970&ids=78342&ids=20825&ids=1087&ids=20294&ids=23775&ids=53360&ids=138573&ids=219616&ids=129922&ids=4384&ids=144952&ids=189366&ids=18428&ids=5564&ids=231258&ids=28059&ids=108517&ids=43977&ids=185115&ids=79093&ids=122793&ids=85731&ids=140737&ids=120033&ids=153568&ids=134646&ids=105172&ids=24385&ids=130163&ids=167764&ids=4729&ids=238139&ids=124445&ids=8030&ids=152525&ids=132959&ids=49463&ids=46422&ids=112380&ids=62437&ids=106055&ids=156061&ids=139562&ids=162684&ids=114547&ids=86526&ids=158621&ids=136105&ids=203014&ids=123012&ids=94687&ids=225103&ids=56383&ids=119279&ids=209072&ids=21616&ids=131703&ids=212737&ids=114956
Traceback (most recent call last):
  File "D:\Programmes 2\Logiciels\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Programmes 2\Logiciels\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\Programmes 2\Logiciels\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Programmes 2\Logiciels\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Programmes 2\Logiciels\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\Programmes 2\Logiciels\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\Programmes 2\Logiciels\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\Programmes 2\Logiciels\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_file_manage.py", line 775, in file_scan
    api_response['items'] = all_items
UnboundLocalError: local variable 'api_response' referenced before assignment
```

### Additional information

I hope you will find a solution because I use your extension on a daily basis. :) It's one of the most useful. Thanks on advance for your attention.

**Comment by BlafKing** [comment]
Thanks for reporting!
And thanks for the kind words about the extension! glad to hear you find it be useful 😄 

It looks like this issue is caused by CivitAI's API, indicated by the line:
```
Error: Received status code 503
```
A common cause for error 503 is a server that is down for maintenance or that is overloaded.
So unfortunately there isn't much that I can do about this, the issue should resolve itself when the servers are working again! :)

I'll add some clearer indication that the issue is being caused by CivitAI's server being either offline or overloaded in an upcoming update to avoid any future confusion for others! :)

**Comment by Rojinski** [comment]
> Thanks for reporting! And thanks for the kind words about the extension! glad to hear you find it be useful 😄
> 
> It looks like this issue is caused by CivitAI's API, indicated by the line:
> 
> ```
> Error: Received status code 503
> ```
> 
> A common cause for error 503 is a server that is down for maintenance or that is overloaded. So unfortunately there isn't much that I can do about this, the issue should resolve itself when the servers are working again! :)
> 
> I'll add some clearer indication that the issue is being caused by CivitAI's server being either offline or overloaded in an upcoming update to avoid any future confusion for others! :)

Thank you so much for your fast answer and your attention. It seems everything is ok today. I was almost sure that it was an issue on the civitai side. Once again, thanks a lot and congratulations for your work!!!

Have a beautiful end of 2023. Stay safe.

Rojinski

**Comment by TheSeventhCode** [comment]
Got this issue as well, but sadly it looks like the extension is then soft-locked, until the UI is reloaded.
For me the UI is then just stuck in the download phase and the `Cancel updating model previews` button just does nothing.
