### ISSUE TITLE
[Bug]: Extension stops working after update to version 988b57c5

### ISSUE THREAD

**Issue by schoenid** [BlafKing/sd-civitai-browser-plus#151]
### Describe the bug.

The extension is unusable.

### Steps to reproduce the problem.

1. Go to ....  Extensions / Installed
2. Press .... Check for updates and Apply and restart
3. ... Try to use it ...

### Expected behavior

Should work as before or better.

### System info

* Extension version: 988b57c5
* OS: Ubuntu Studio 22.04
* SD-WebUI version: v1.6.0
* Python: 3.10.12

### Console logs

```Shell
*** Error executing callback ui_settings_callback for /home/sd/Games/stable-diffusion-webui/extensions/sd-civitai-browser-plus/scripts/civitai_gui.py
    Traceback (most recent call last):
      File "/home/sd/Games/stable-diffusion-webui/modules/script_callbacks.py", line 184, in ui_settings_callback
        c.callback()
      File "/home/sd/Games/stable-diffusion-webui/extensions/sd-civitai-browser-plus/scripts/civitai_gui.py", line 815, in on_ui_settings
        from modules.options import categories
    ImportError: cannot import name 'categories' from 'modules.options' (/home/sd/Games/stable-diffusion-webui/modules/options.py)

---
```

**Comment by schoenid** [comment]
Removed it completely and reinstalled it with the same problem.

**Comment by schoenid** [comment]
I did an update of the webui to 1.7.0

No problems now.

**Comment by BlafKing** [comment]
Thanks for reporting!

This issue is indeed fixed by using the latest version, but I intended for it to work on older versions as well, so thank for pointing this out, the latest version should now also work on older versions of SD-WebUI! :)
