### ISSUE TITLE
[Bug]: After updating models, cannot use search

### ISSUE THREAD

**Issue by kmillerdevx3** [BlafKing/sd-civitai-browser-plus#156]
### Describe the bug.

Seems to be the inverse of https://github.com/BlafKing/sd-civitai-browser-plus/issues/145

After using the Update Models tab, trying to perform a new search results in "Error" on all visible fields, search results are not updated. Requires a Reload UI to reset.

### Steps to reproduce the problem.

1. Go to "Update Models" tab and choose an update category
2. Press "Scan for available updates", then "Load outdated models to browser"
3. Go to "Browser" tab and note that updated models are listed in the search results. (Optional, update any or all models - doesn't seem to affect the bug
4. Enter any search term into the search box, and hit enter or press the magnifying glass. System will attempt to perform the search (all fields show progress bars, etc.) followed by "Error" label on all fields

### Expected behavior

After loading out-of-date models into the browser tab, search should function as normal.

### System info

* Extension version: [3.2.0](https://github.com/BlafKing/sd-civitai-browser-plus/commit/d21758863a0605f5139b1f5f49af0a4e00880b02) (December 21, 2023)
* OS: Windows 10
* SD-WebUI version: 1.7.0
* Python: 3.10.4

### Console logs

```Shell
n/a (nothing is logged when this occurs)
```

**Comment by BlafKing** [comment]
Thanks for reporting!

This issue should now be fixed in [v3.2.2](https://github.com/BlafKing/sd-civitai-browser-plus/commit/e17e5ca6795d61d186706e6a7100372bcc860031)

I'll go ahead and close this bug report, but feel free to send another message if you find that the issue still exists! :)
