### ISSUE TITLE
[Bug]: Models that link to an Internal Service Error will cause Civitai Browser to fail

### ISSUE THREAD

**Issue by Terroosh** [BlafKing/sd-civitai-browser-plus#157]
### Describe the bug.

Some models link to a 500: Internal Service Error on Civitai like the following: 
https://civitai.com/models/254371/ganjarpranowo?modelVersionId=286768
![1](https://github.com/BlafKing/sd-civitai-browser-plus/assets/55752005/e4312b16-9fd9-4d13-ac3b-833317837559)

This model still shows when searching models on Civitai's own site but links to an error page. Maybe models like this are being scheduled for deletion or flagged by civitai. This is causing Civitai browser to fail if the model shows up in the search results:

`CivitAI Browser+: Error: 500 Server Error: Internal Server Error for url: https://civitai.com/api/v1/models?limit=50&page=1&&ids=254371`

### Steps to reproduce the problem.

1. Put https://civitai.com/models/254371/ganjarpranowo?modelVersionId=286768  into civitai browser
2. Error occurs

### Expected behavior

Model is ignored if possible

### System info

* Extension version: 3.2.1
* OS: Win 11
* SD-WebUI version: 1.6
* Python: 3.10.6

### Console logs

```Shell
CivitAI Browser+: Error: 500 Server Error: Internal Server Error for url: https://civitai.com/api/v1/models?limit=50&page=1&&ids=254371
```

**Comment by BlafKing** [comment]
This issue wasn't fixable by myself, since I cannot detect when a model would've returned an error.

I did however report it as soon as I experienced it myself to the CivitAI github and thankfully it has now already been fixed by the CivitAI team, so I'll go ahead and close this bug report! :)
