### ISSUE TITLE
[Bug]: Scaling buttons on cards

### ISSUE THREAD

**Issue by Yaruze66** [BlafKing/sd-civitai-browser-plus#162]
### Describe the bug.

By default, along with text scaling, the sizes of the icon buttons on the cards are also scaled, but the size of the icon button in the extension does not scale with them.

1.0 vs. 0.75
![1](https://github.com/BlafKing/sd-civitai-browser-plus/assets/138091206/83879d97-4259-4c37-8d98-d7957fca85fa) ![0 75](https://github.com/BlafKing/sd-civitai-browser-plus/assets/138091206/824dede3-a17c-48c1-ae47-af91dd5c5e46)

### Steps to reproduce the problem.

1. Go to Settings -> Extra Networks
2. Set the value of "Card text scale" (extra_networks_card_text_scale) other than 1.0

### Expected behavior

I'm not entirely sure that the buttons on the cards should scale along with the text, but at least before that I used the [Stable-Diffusion-Webui-Civitai-Helper](https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper) extension, in which scaling worked.

### System info

* Extension version: [281cdc0](https://github.com/BlafKing/sd-civitai-browser-plus/commit/281cdc048939e6f6c18766ffeb5e18c00c20e2d2)
* OS: Windows 11 Pro 23H2 (22631.3007)
* SD-WebUI version: [v1.6.0-2-g4afaaf8a](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/4afaaf8a020c1df457bcf7250cb1c7f609699fa7)
* Python: 3.10.6

### Console logs

```Shell
venv "D:\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.6.0-2-g4afaaf8a
Commit hash: 4afaaf8a020c1df457bcf7250cb1c7f609699fa7
Launching Web UI with arguments: --theme dark --xformers
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
[-] ADetailer initialized. version: 24.1.1, num models: 9
CivitAI Browser+: Aria2 RPC started
ControlNet preprocessor location: D:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2024-01-12 02:11:06,063 - ControlNet - INFO - ControlNet v1.1.430
2024-01-12 02:11:06,170 - ControlNet - INFO - ControlNet v1.1.430
Loading weights [6ce0161689] from D:\stable-diffusion-webui\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 13.7s (prepare environment: 3.5s, import torch: 3.2s, import gradio: 0.8s, setup paths: 0.7s, initialize shared: 0.2s, other imports: 0.5s, setup codeformer: 0.1s, load scripts: 3.7s, create ui: 0.7s, gradio launch: 0.2s).
Creating model from config: D:\stable-diffusion-webui\configs\v1-inference.yaml
Applying attention optimization: xformers... done.
Model loaded in 4.0s (load weights from disk: 1.8s, create model: 0.3s, apply weights to model: 1.5s, calculate empty prompt: 0.1s).
```

**Comment by BlafKing** [comment]
Thanks for reporting!

I've published a new version which should properly handle the scaling compared to the other buttons! :)
