### ISSUE TITLE
[Bug]: Typo

### ISSUE THREAD

**Issue by ManOrMonster** [BlafKing/sd-civitai-browser-plus#166]
### Describe the bug.

I can't believe it took me this long to notice this. In my defense I usually use this first thing in the morning. 😆

In [scripts/civitai_gui.py, line 206](https://github.com/BlafKing/sd-civitai-browser-plus/blob/281cdc048939e6f6c18766ffeb5e18c00c20e2d2/scripts/civitai_gui.py#L206):

`download_selected = gr.Button(value="Download all 👉seleceted👈", interactive=False, visible=False)`

### Steps to reproduce the problem.

1. Check more than one model
2. Look at misspelled button

### Expected behavior

Should say "selected"

### System info

* Extension version: Latest
* OS: Apple ][ e (ProDos)
* SD-WebUI version: ComfyUI
* Python: 48 inches

### Console logs

```Shell
n/a
```

**Comment by BlafKing** [comment]
Nice catch!

Never noticed that myself either 😅
I have fixed in the latest version! :)
