### ISSUE TITLE
[Bug]: Defaults to downloading zip file instead of safetensors

### ISSUE THREAD

**Issue by Pemmican6** [BlafKing/sd-civitai-browser-plus#172]
### Describe the bug.

When selecting a model card, the file: field will fill in with the safetensors file, but the model filename: field will contain the zip file for the other file in the model tree.
Only by switching safetensor to other, and back can I get the safetensor file to download

### Steps to reproduce the problem.

1. search on user named mnemic
2. select gelato style
3. gui will show safetensor file, but zip model filename.
![image](https://github.com/BlafKing/sd-civitai-browser-plus/assets/9336408/1a1526cb-e976-486a-a381-fae8f3d37852)

### Expected behavior

expected behavior is to default to the safetensor file

### System info

* Extension version:01/13/2024
* OS:Windows
* SD-WebUI version:Automatic1111
* Python:3.10.6

### Console logs

```Shell
there are no error messages
```

**Comment by BlafKing** [comment]
Thanks for reporting!

This issue is now fixed in ([v3.2.5](https://github.com/BlafKing/sd-civitai-browser-plus/commit/c3129a7fd3d4cc63378027725e8fc67de15fdedb))! :)

I'll go ahead and close this issue, feel free to send another message here if you the issue somehow still persists!
