### ISSUE TITLE
[Bug]: In addition to the solved issue #170, there are another two small problems

### ISSUE THREAD

**Issue by Git-Maniac** [BlafKing/sd-civitai-browser-plus#175]
### Describe the bug.

If multiple models have the same name:

- no checkmarks visible in any selection
- selection frame stacks on the 1st selection

### Steps to reproduce the problem.

See Issue #170

### Expected behavior

See Issue #170

### System info

See Issue #170

### Console logs

```Shell
See Issue #170
```

### Additional information

Not a real problem, just confusing.

**Comment by BlafKing** [comment]
I unfortunately can't seem to recreate these issues, if I understand you correct that is:

https://github.com/BlafKing/sd-civitai-browser-plus/assets/9644716/9a424986-c9fe-4187-9620-515e04442fae

**Comment by Git-Maniac** [comment]
Sorry, I misunderstood the concept of frame and checkboxes. 

If you've donwloaded models already, you cannot checkbox them anymore and frame stack around all the downloaded once. 

I understand now. It's not a bug, it's my mistake.

**Comment by Git-Maniac** [comment]
Sorry, I misunderstood the concept of frame and checkboxes. 

If you've donwloaded models already, you cannot checkbox them anymore and frame stack around all the downloaded once. 

I understand now. It's not a bug, it's my mistake.
