### ISSUE TITLE
[Bug]: fails to decode JSON containg unicode

### ISSUE THREAD

**Issue by curiousjp** [BlafKing/sd-civitai-browser-plus#177]
### Describe the bug.

Some models embed utf-8 escape sequences in their json files (but contain no BOM marker) - for example, [DynaVision XL](https://civitai.com/api/v1/models/122606) uses ❤️, unicode code point U+2764, which is represented in utf-8 as 0xe2 0x9d 0xa4.

If you have a model like this installed on your system, actions involving the elements of the Civitai Browser+ script that check for installed versions will produce the following on the console:
```
CivitAI Browser+: failed to read: "dynavisionXLAllInOneStylized_releaseV0610Bakedvae.json": 'charmap' codec can't decode byte 0x9d in position 1332: character maps to <undefined>
CivitAI Browser+: Error decoding JSON: 'charmap' codec can't decode byte 0x9d in position 1332: character maps to <undefined>
```
(See the further context section for more information.)

### Steps to reproduce the problem.

1. Install DynaVision XL through Civitai Browser plus.
2. Search up another model using Civitai Browser plus.
3. Click on the model tiles while watching the console.

### Expected behavior

No error messages related to failed unicode decoding should be printed to the console.

### System info

* Extension version: [9e70db57](https://github.com/BlafKing/sd-civitai-browser-plus/commit/9e70db57c5ecd12868fe44f63df5043c6f4a241a)
* OS: Windows 11
* SD-WebUI version: Version: v1.7.0 / commit hash: cf2772fab0af5573da775e7437e6acdca424f26e
* Python: Python 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]

### Console logs

```Shell
Total progress: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.97s/it]
CivitAI Browser+: Error decoding JSON in E:\...\webui\models\Stable-diffusion\dynavisionXLAllInOneStylized_releaseV0610Bakedvae.json: 'charmap' codec can't decode byte 0x9d in position 1332: character maps to <undefined>
CivitAI Browser+: failed to read: "dynavisionXLAllInOneStylized_releaseV0610Bakedvae.json": 'charmap' codec can't decode byte 0x9d in position 1332: character maps to <undefined>
CivitAI Browser+: Error decoding JSON: 'charmap' codec can't decode byte 0x9d in position 1332: character maps to <undefined>
```

### Additional information

When interrogating the file handle opened at line 857 of civitai_api.py, it has its encoding set to cp1252, which is confusing as sys.getdefaultencoding() returns utf-8 at this time, and cp1252 does not appear to be manually set. The problem can be worked around by setting the PYTHONUTF8 environment variable (e.g. through webui-user.bat) but it seems it would be better to manually specify the encoding= keyword argument to both JSON related calls to open().

**Comment by BlafKing** [comment]
Thanks for reporting!

I'll include your suggested solution into the next update to avoid this issue! :)

**Comment by Git-Maniac** [comment]
I can confirm a simular issue with Japanese LoRAs. Probably it has Japanese chars in JSON file:

CivitAI Browser+: Error decoding JSON in D:\Stable Diffusion WebUI\stable-diffusion-webui\models\Lora\Covering\MK_kzy_xl_V1.0.json: 'charmap' codec can't decode byte 0x8d in position 174: character maps to <undefined>
CivitAI Browser+: Error decoding JSON in D:\Stable Diffusion WebUI\stable-diffusion-webui\models\Lora\Covering\qingqu_XL_reg0_.json: 'charmap' codec can't decode byte 0x81 in position 288: character maps to <undefined>
CivitAI Browser+: Error decoding JSON in D:\Stable Diffusion WebUI\stable-diffusion-webui\models\Lora\Japanese\Reiko.json: 'charmap' codec can't decode byte 0x9d in position 250: character maps to <undefined>

**Comment by BlafKing** [comment]
Thanks for reporting!

This should now be fixed in the latest version! :)
