### ISSUE TITLE
[Bug]: download does not start

### ISSUE THREAD

**Issue by johnnycaifan** [BlafKing/sd-civitai-browser-plus#179]
### Describe the bug.

https://github.com/BlafKing/sd-civitai-browser-plus/assets/35149660/ada817c6-09b5-4433-928c-e5c5c853c98c

### Steps to reproduce the problem.

1. Go to .... civitai browser
2. Press .... download
3. ...no se inicia la descarga

### Expected behavior

I send a video showing the problem

### System info

* Extension version:
* OS:
* SD-WebUI version:
* Python:

### Console logs

```Shell
I send a video showing the problem
```

**Comment by BlafKing** [comment]
As stated in the text on the screen and in the console logs, you need to set a personal API key to be able to download that file.
```
"requires a personal CivitAI API to be downloaded, you can et your own API key in the CivitAI Browser+ settings in the SD-WebUI settings tab"
```

You can open the settings tab of SD-WebUI, there you can find the settings for CivitAI Browser+ where you can fill in your personal CivitAI API Key, you can create an API key in your [CivitAI account settings](https://civitai.com/user/account)
