### ISSUE TITLE
[Bug]: Civitai button modal is too big on tablet portrait view

### ISSUE THREAD

**Issue by ManOrMonster** [BlafKing/sd-civitai-browser-plus#187]
### Describe the bug.

The new HTML modal is slightly too wide on my tablet in portrait view. This cuts off some text, and also makes it impossible to close because the modal takes up the entire window.

### Steps to reproduce the problem.

1. Press Civitai button
2. Look around in vain for way to close modal

### Expected behavior

Everything shoould fit in view and the modal should be able to be closed.

### System info

* Extension version:
* OS:
* SD-WebUI version:
* Python:

### Console logs

```Shell
Nuthin
```

### Additional information

Putting a margin at the top of .civitaiOverlay would at least make it closable.

**Comment by BlafKing** [comment]
Thanks for reporting!

I'll make sure to publish a fix somewhere today!

**Comment by BlafKing** [comment]
This should now be fixed in the latest version (v3.3.1)

Took a lil longer than intended but oh well, thanks again for reporting it! :)
