### ISSUE TITLE
[Bug]: Update Models and Tags returns: ValueError: could not convert string to float: 'full'

### ISSUE THREAD

**Issue by 3mong0ose** [BlafKing/sd-civitai-browser-plus#192]
### Describe the bug.

when i run the scan of the folders to get info for the manually added models I keep getting: File "E:\Programs\Auto1111SDWebUI\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_[api.py](http://api.py/)", line 736, in update_model_info

if float(file_list[0].split(' ')[0]) <= 100:

ValueError: could not convert string to float: 'full'

I have to restart the web app after.

Is something corrupted? I removed the last file but then it stops at another one... I gave up after I moved 30 models out of the folder and it was still hanging up. Some are models/loras I've recently downloaded. I deleted the wbui vnv folder and the civit web ui + folder from my extensions 3 times now. I tried rolling back my civit+ plug in to a version from december. I added an api key to the webui. no change. I also tried deleting just the .json for the file listed in the console still hung up on the file. This happens even if i uncheck "Overwrite any existing previews, tags or descriptions."

Hide

### Steps to reproduce the problem.

1. Go to .... civit browser+ tab > Update models >
2. Press .... "Update Models and Tags" button
3. ...

### Expected behavior

The files should scan though on the console updating each model's .json and other files. If a bad or unrecognised file is encountered, it's listed and the scan continues.

### System info

* Extension version: 177ce5d1
* OS:Windows 10
* SD-WebUI version: v1.7.0 
* Python: python: 3.10.6

### Console logs

```Shell
=======proceeded by many models passing====================================================
CivitAI Browser+: Model info saved to "E:\Programs\Auto1111SDWebUI\stable-diffusion-webui\models\Lora\angry_v1.json"
CivitAI Browser+: Model info saved to "E:\Programs\Auto1111SDWebUI\stable-diffusion-webui\models\Lora\anishaded_v2.json"
CivitAI Browser+: Model info saved to "E:\Programs\Auto1111SDWebUI\stable-diffusion-webui\models\Lora\annaChlumsky_v10.json"
CivitAI Browser+: Model info saved to "E:\Programs\Auto1111SDWebUI\stable-diffusion-webui\models\Lora\anneHathaway_v10.json"
CivitAI Browser+: Model info saved to "E:\Programs\Auto1111SDWebUI\stable-diffusion-webui\models\Lora\ariaSky_v10.json"
CivitAI Browser+: Model info saved to "E:\Programs\Auto1111SDWebUI\stable-diffusion-webui\models\Lora\arielLilitAFemjoyMetArt_arielManualcut.json"
CivitAI Browser+: Model info saved to "E:\Programs\Auto1111SDWebUI\stable-diffusion-webui\models\Lora\asd-000009.json"
CivitAI Browser+: Model info saved to "E:\Programs\Auto1111SDWebUI\stable-diffusion-webui\models\Lora\ashley_10.json"
CivitAI Browser+: Model info saved to "E:\Programs\Auto1111SDWebUI\stable-diffusion-webui\models\Lora\assOnGlasses_v10.json"
CivitAI Browser+: Model info saved to "E:\Programs\Auto1111SDWebUI\stable-diffusion-webui\models\Lora\ass_size_control_v2.0.json"
CivitAI Browser+: Model info saved to "E:\Programs\Auto1111SDWebUI\stable-diffusion-webui\models\Lora\attackingConcept_18.json"
CivitAI Browser+: Model info saved to "E:\Programs\Auto1111SDWebUI\stable-diffusion-webui\models\Lora\avril.fp16.json"
CivitAI Browser+: Model info saved to "E:\Programs\Auto1111SDWebUI\stable-diffusion-webui\models\Lora\backlight_slider_v10.json"
Traceback (most recent call last):
  File "E:\Programs\Auto1111SDWebUI\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\Programs\Auto1111SDWebUI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "E:\Programs\Auto1111SDWebUI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\Programs\Auto1111SDWebUI\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\Programs\Auto1111SDWebUI\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\Programs\Auto1111SDWebUI\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\Programs\Auto1111SDWebUI\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "E:\Programs\Auto1111SDWebUI\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_file_manage.py", line 956, in file_scan
    preview_html = _api.update_model_info(None, model_versions.get('value'), True, id_value, api_response)
  File "E:\Programs\Auto1111SDWebUI\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 736, in update_model_info
    if float(file_list[0].split(' ')[0]) <= 100:
ValueError: could not convert string to float: 'full'
```

### Additional information

Im unable to cancel the process in the web ui browser window. I have to use the apply and restart ui in the web ui extensions tab or close the console window and start over. 

Maybe i'm missing something and this is not a bug?

**Comment by BlafKing** [comment]
Thanks for reporting!

I'll attempt to include a fix for this in the upcoming update!

**Comment by BlafKing** [comment]
I've now published a new update which should hopefully resolve this issue (v3.3.1)

Please let me know if you're still experiencing this issue! :)

**Comment by 3mong0ose** [comment]
It appears to be fixed! All models scanned successfully.

**Comment by BlafKing** [comment]
Awesome! Glad to hear :)
