### ISSUE TITLE
[Bug]: 'Store the HTML and api_info in the custom images location' not working.

### ISSUE THREAD

**Issue by hakaserver** [BlafKing/sd-civitai-browser-plus#195]
### Describe the bug.

The new option 'Store the HTML and api_info in the custom images location' is not being respected, they are still saved in the 'Download folder' location.

### Steps to reproduce the problem.

1. Enable 'Store the HTML and api_info in the custom images location'.
2. Set a 'Custom save images location'.
3. Enable 'Save API info of model when saving model info'
4. Enable 'Automatically save all images'
5. Either press 'Save model info' or 'Download model'.
6. Both .api_info.json and .html files are saved in the 'Download folder'.

### Expected behavior

Either manually pressing 'Save model info' or when downloading automatically when pressing 'Download model', both .api_info.json and .html files are expected to be downloaded in the 'Custom save images location' folder and selected subfolder.

### System info

* Extension version: e4ef29af
* OS: Win11
* SD-WebUI version: 1.7.0
* Python: 3.10.6

### Console logs

```Shell
CivitAI Browser+: Model saved to: H:\SDWebui\stable-diffusion-webui\models\Lora\Subfolder\*model*.safetensors
CivitAI Browser+: Model info saved to "H:\SDWebui\stable-diffusion-webui\models\Lora\Subfolder\*model*.json"
CivitAI Browser+: Preview saved at "H:\SDWebui\stable-diffusion-webui\models\Lora\Subfolder\*model*.preview.png"
CivitAI Browser+: Downloaded *model*_0.png
CivitAI Browser+: Downloaded *model*_1.png
CivitAI Browser+: Downloaded *model*_2.png
CivitAI Browser+: Downloaded *model*_3.png

Obs.: Custom save images location set to: 'H:\SDWebui\stable-diffusion-webui\models_db'. Sample images are correctly saved to 'H:\SDWebui\stable-diffusion-webui\models_db\Lora\Subfolder\'
```

**Comment by hakaserver** [comment]
Found the problem, it was a quick fix!
Made a pull request https://github.com/BlafKing/sd-civitai-browser-plus/pull/196 . ✌️

**Comment by BlafKing** [comment]
Merged! Thanks for reporting :)
