### ISSUE TITLE
Feature Request: Page Selection

### ISSUE THREAD

**Issue by ManOrMonster** [BlafKing/sd-civitai-browser-plus#2]
This extension is already a dream finally realized for me. Thanks!

**Issue**: If something goes wrong while browsing many pages, it can be a pain to get back to the last page you were at.

**Solution**: The page display should instead be a select dropdown, where you can choose the page to jump to (e.g. "2/24",."18/24", and so on).

**Comment by BlafKing** [comment]
There is already a function that allows you to input the page number you want to visit, you can fill in the page you'd like to go to and press Refresh, this will get you to the page you'd like to visit.  
Gradio (the UI library used by A1111) doesn't always receive user inputs when typed quickly, so you can press enter to make sure the new page number is successfully submitted.


https://github.com/BlafKing/sd-civitai-browser-plus/assets/9644716/28fbe793-fcd6-4422-a7df-133f2a5753d8

**Comment by BlafKing** [comment]
There is already a function that allows you to input the page number you want to visit, you can fill in the page you'd like to go to and press Refresh, this will get you to the page you'd like to visit.  
Gradio (the UI library used by A1111) doesn't always receive user inputs when typed quickly, so you can press enter to make sure the new page number is successfully submitted.


https://github.com/BlafKing/sd-civitai-browser-plus/assets/9644716/28fbe793-fcd6-4422-a7df-133f2a5753d8

**Comment by ManOrMonster** [comment]
I thought that would be the functionality, but when I tried it, it didn't work for me. Just tried it again and it worked.

Another option would be to make the page input separate from the total pages, so that you can only edit the current page number, while also making it more obvious that it works this way.

Exemple:
<img width="92" alt="image" src="https://github.com/BlafKing/sd-civitai-browser-plus/assets/3925151/fbd4aef5-38fa-46b9-8219-161625b3bd42">
