### ISSUE TITLE
[Bug]: Incorrect Functionality of [Base Model] and [Version Name] When Setting [/Base Model/Author Name/Model Name/Version Name] in [Default Subfolders]

### ISSUE THREAD

**Issue by AnbaiMei** [BlafKing/sd-civitai-browser-plus#217]
### Describe the bug.

If you set [/Base model/Author name/Model name/Version name] in the [Default sub folders], [Base model] and [Version name] will not function correctly. 
In the case of EasyNegative, '/Havoc/Havoc/EasyNegative/Version name' is set.

### Steps to reproduce the problem.

1. [Settings]->[Browser]->[Insert sub folder options]->[Insert: [/Base model/Author name/Model name/Model version]]
2. [Settings]->[Downloads]->[Default sub folders]->[/Base model/Author name/Model name/Version name]
3. Search for 'EasyNegative' on the CivitAI Browser and select it.

### Expected behavior

It is set to the subfolder '/SD 1.5/Havoc/EasyNegative/EasyNegative'.

### System info

* Extension version:bcf6c1872b8df05d359142bd87cb28fafdb3f9a7
* OS:macOS 13.6.4
* SD-WebUI version:v1.7.0
* Python:3.10.13

### Console logs

```Shell
There are no error messages.
```

**Comment by BlafKing** [comment]
Thanks for reporting!

Will publish a fix for this in the next update!

**Comment by AnbaiMei** [comment]
Thank you for your reply!

I believe this extension is the most excellent among all the Civitai extensions.
Thank you very much for always maintaining and adding new features.

**Comment by BlafKing** [comment]
Appreciate the kind words! Glad to hear you like the extension :)

Took a little long to publish this update, sry bout that, got sick and didn't have much time 😅 

Regardless, I'll mark this is as resolved now as the issue should no longer occur! 👍🏻
