### ISSUE TITLE
[Bug]: GradioUnusedKwargWarning: You have unused kwarg parameters in Slider

### ISSUE THREAD

**Issue by D0n-A** [BlafKing/sd-civitai-browser-plus#222]
### Describe the bug.

Hello. I think you are aware of this little thing, but when installing the extension on the latest version of AUTOMATIC 1111, warning appear, which I described in the corresponding feedback section.

### Steps to reproduce the problem.

1. Install a clean repository SD on Windows;
2. Install it as usual;
3. Activate the corresponding item in the repository settings: "Show warnings in console";
4. Close the command line and restart the interface;
5. Warning.

### Expected behavior

Make a small adjustment so that this warning disappears and does not visually interfere.

### System info

* Extension version: [bcf6c187](https://github.com/BlafKing/sd-civitai-browser-plus/commit/bcf6c1872b8df05d359142bd87cb28fafdb3f9a7)
* OS: Windows 11
* SD-WebUI version: [1.8.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/bef51aed032c0aaa5cfd80445bc4cf0d85b408b5)
* Python: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]

### Console logs

```Shell
...
...
...
D:\AI\NS\modules\gradio_extensons.py:25: GradioUnusedKwargWarning: You have unused kwarg parameters in Slider, please remove them: {'max_width': 100}
  res = original_IOComponent_init(self, *args, **kwargs)
...
...
...
```

**Comment by BlafKing** [comment]
Thanks for reporting!

This should now be fixed in the latest version so I'll mark this as resolved 👍🏻
