### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by emogie** [BlafKing/sd-civitai-browser-plus#224]
### Describe the bug.

permission of models, loras, etc are not displayed correctly especially these one from allowCommercialUse

### Steps to reproduce the problem.

1. Go to civitai-browser-plus
2. performa a search for models, and compare the permission with the one in Civitai.com, except of allowCommercialUse all will be displayed correctly, the var allowCommercialUse can contain up to 4 values.

# all allowed - example: Real Dream
"allowNoCredit":true,
"allowCommercialUse":["Image","RentCivit","Rent","Sell"],
"allowDerivatives":true,
"allowDifferentLicense":true,

# all forbidden - example: Platinum Noir Smooth
"allowNoCredit":false,
"allowCommercialUse":[],
"allowDerivatives":false,
"allowDifferentLicense":false,

### Expected behavior

displaying of correct values, like on CivitAI

### System info

* Extension version: 
* OS: Win 11 x64
* SD-WebUI version: A1111 1.7.0 - custom modified
* Python: 3.11.8

### Console logs

```Shell
none
```

### Additional information

please change in civitai_api.py on line 882, or create a better solution (i created for my purposes only a quick and dirty solution)

from

perms_html= '<p style="line-height: 2; font-weight: bold;">'\
                            f'{allow_svg if item.get("allowNoCredit") else deny_svg} Use the model without crediting the creator<br/>'\
                            f'{allow_svg if item.get("allowCommercialUse") in ["Image", "Rent", "RentCivit", "Sell"] else deny_svg} Sell images they generate<br/>'\
                            f'{allow_svg if item.get("allowCommercialUse") in ["Rent", "Sell"] else deny_svg} Run on services that generate images for money<br/>'\
                            f'{allow_svg if item.get("allowCommercialUse") in ["RentCivit", "Rent", "Sell"] else deny_svg} Run on Civitai<br/>'\
                            f'{allow_svg if item.get("allowDerivatives") else deny_svg} Share merges using this model<br/>'\
                            f'{allow_svg if item.get("allowCommercialUse") == "Sell" else deny_svg} Sell this model or merges using this model<br/>'\
                            f'{allow_svg if item.get("allowDifferentLicense") else deny_svg} Have different permissions when sharing merges'\
                            '</p>'
to

put all values from array allowCommercialUse to a python readable one
                
                # print(', '.join(perm_allowCommercialUse)) # Debug purpose only
                # SideNote; return as bool true if contains value 'RentCivit' -> binary comparison (as a 2nd value called 'Rent' exists) 
                # example: if any("RentCivit" == s for s in perm_allowCommercialUse)

                perm_allowCommercialUse = item.get("allowCommercialUse", [])
                perms_html= '<p style="line-height: 2; font-weight: bold;">'\
                            f'{allow_svg if item.get("allowNoCredit") else deny_svg} Use the model without crediting the creator<br/>'\
                            f'{allow_svg if any("Image" == s for s in perm_allowCommercialUse) else deny_svg} Sell images they generate<br/>'\
                            f'{allow_svg if any("RentCivit" == s for s in perm_allowCommercialUse) else deny_svg} Run on services that generate images for money<br/>'\
                            f'{allow_svg if any("Rent" == s for s in perm_allowCommercialUse) else deny_svg} Run on Civitai<br/>'\
                            f'{allow_svg if item.get("allowDerivatives") else deny_svg} Share merges using this model<br/>'\
                            f'{allow_svg if any("Sell" == s for s in perm_allowCommercialUse) else deny_svg} Sell this model or merges using this model<br/>'\
                            f'{allow_svg if item.get("allowDifferentLicense") else deny_svg} Have different permissions when sharing merges'\
                            '</p>'

thanks in advance

**Comment by BlafKing** [comment]
Thanks for reporting!

I've posted a new commit with a hotfix that should solve this issue.
I'll mark this as resolved 👍🏻
