### ISSUE TITLE
[Bug]: Preview image not downloading

### ISSUE THREAD

**Issue by Terroosh** [BlafKing/sd-civitai-browser-plus#236]
### Describe the bug.

The preview image doesn't seem to be downloaded anymore when downloading a model, example model:

https://civitai.com/models/354133

### Steps to reproduce the problem.

1. Download the model
2. Preview image does not get saved

### Expected behavior

Preview image gets saved

### System info

* Extension version: https://github.com/BlafKing/sd-civitai-browser-plus/commit/b56d738d2931a805796f1265e2bb6c7442d60534
* OS: Win 11
* SD-WebUI version: 1.8
* Python: 3.10.6

### Console logs

```Shell
CivitAI Browser+: Model saved to: K:\SD A1111\models\Lora\PCMR_v1.safetensors
CivitAI Browser+: Model info saved to "K:\SD A1111\models\Lora\PCMR_v1.json"
```

**Comment by Terroosh** [comment]
Adding the model to a download queue by clicking the checkmark box on the image will allow the preview image to download but clicking "Download Model" will not download a preview image.

**Comment by BlafKing** [comment]
Thanks again for reporting!

This error occurred if the model did not have it's hashes generated yet, posted a little hotfix that should download the preview image in both cases if a hash is not found! :)

I'll mark this as resolved 👍🏻
