### ISSUE TITLE
[Bug]: Cannot refresh checkpoint page on txt2img and img2img

### ISSUE THREAD

**Issue by skyfall086** [BlafKing/sd-civitai-browser-plus#239]
### Describe the bug.

Cannot use "refresh page" button on checkpoint page on txt2img and img2img

### Steps to reproduce the problem.

1. Go to txt2img or img2img
2. Press Checkpoints tab
3. Click refresh page button in the top right corner
4. Nothing happens

### Expected behavior

It should refresh the checkpoint page after click the button. Disabling the extension can fix the issue.

### System info

* Extension version: main 3.5.0 c6f41ad
* OS: Windows 11
* SD-WebUI version: v1.8.0
* Python: 3.10.9

### Console logs

```Shell
None
```

**Comment by wangzan1990** [comment]
same issue

**Comment by BlafKing** [comment]
Thanks for reporting!

I'll post a hotfix for this shortly.

**Comment by BlafKing** [comment]
The latest commit should fix the issue, thanks again for reporting!

I'll mark this as resolved 👍🏻
