### ISSUE TITLE
[Bug]: causes a1111 webui to hang

### ISSUE THREAD

**Issue by maz323f** [BlafKing/sd-civitai-browser-plus#240]
### Describe the bug.

When installed the extension causes problem for automatic1111, the webui freezes.
if you create 4-5 images and start browsing thru them in freezes. if you send an image to img2img, and work with it the webui freezes.

but when the civitai browser extension if disabeled it all works fine.,.

### Steps to reproduce the problem.

Create 4 images, and browse thru them
send image to img2img and work on it the webui freezes

### Expected behavior

expecting the webui not to freeze when civitai browser pluss in enabeled in the extension tab.

### System info

version: [v1.8.0]
python: 3.10.6 
torch: 2.1.2+cu121
 xformers: 0.0.23.post1 

### Console logs

```Shell
venv "D:\AI\Automatic1111\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.8.0
Commit hash: bef51aed032c0aaa5cfd80445bc4cf0d85b408b5
Faceswaplab : Use GPU requirements
Checking faceswaplab requirements
0.0034684999845921993
Launching Web UI with arguments: --api --xformers --port 8080 --autolaunch --ckpt-dir ../AI-MODELS/Stable-diffusion --codeformer-models-path ../AI-MODELS/Codeformer/ --gfpgan-models-path ../AI-MODELS/GFPGAN --esrgan-models-path ../AI-MODELS/ESRGAN --bsrgan-models-path ../AI-MODELS/BSRGAN --realesrgan-models-path ../AI-MODELS/RealESRGAN --scunet-models-path ../AI-MODELS/ScuNET --swinir-models-path ../AI-MODELS/SwinIR --ldsr-models-path ../AI-MODELS/LDSR --lora-dir ../AI-MODELS/Lora
[-] ADetailer initialized. version: 24.3.1, num models: 15
CivitAI Browser+: Aria2 RPC started
ControlNet preprocessor location: D:\AI\Automatic1111\extensions\sd-webui-controlnet\annotator\downloads
2024-03-20 01:34:56,905 - ControlNet - INFO - ControlNet v1.1.441
2024-03-20 01:34:56,961 - ControlNet - INFO - ControlNet v1.1.441
Loading weights [aeb7e9e689] from D:\AI\Automatic1111\..\AI-MODELS\Stable-diffusion\SDXL\Juggernaut XL\V 8 + RunDiffusion\juggernautXL_v8Rundiffusion.safetensors
Creating model from config: D:\AI\Automatic1111\repositories\generative-models\configs\inference\sd_xl_base.yaml
Applying attention optimization: xformers... done.
Model loaded in 3.1s (create model: 0.2s, apply weights to model: 2.4s, load textual inversion embeddings: 0.1s, calculate empty prompt: 0.2s).
2024-03-20 01:35:01,434 - ControlNet - INFO - ControlNet UI callback registered.
*Deforum ControlNet support: enabled*
Loading general settings...
reading custom settings from D:\AI\Automatic1111\deforum_settings.txt
The custom settings file does not exist. The values will be unchanged.
Running on local URL:  http://127.0.0.1:8080

To create a public link, set `share=True` in `launch()`.
Startup time: 15.0s (prepare environment: 3.0s, import torch: 2.1s, import gradio: 0.5s, setup paths: 0.5s, initialize shared: 0.2s, other imports: 0.4s, load scripts: 2.9s, create ui: 4.9s, gradio launch: 0.2s, add APIs: 0.4s).
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:11<00:00,  1.82it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:13<00:00,  1.52it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:13<00:00,  1.91it/s]
```

**Comment by BlafKing** [comment]
Thanks for reporting,
I suspect this may be caused by unoptimized javascript functions running in the background, as no other code should be running when the CivitaAI tab is not opened.

I'll try to do some testing tomorrow, as I am personally not experiencing any of the problems you mentioned, thanks for bringing it to my attention though, could you also provide what hardware you are using to browse and run SD-WebUI?

**Comment by maz323f** [comment]
did notice there was an update to the extension yesterday! seems to have fixed my problem 
https://github.com/BlafKing/sd-civitai-browser-plus/commit/e527eead12b949b133b23c28b3a1b3c9351bc8e7

did a fresh install of a1111 and forge with my extensions that i use yesterday, only guessing i did this right before u had this new commit out and thats why i did experiencing this problem i had.

**Comment by BlafKing** [comment]
Awesome! glad to hear.

I'll mark this as resolved :)
