### ISSUE TITLE
[BUG] Non-model files being checked for updates alongside the valid files

### ISSUE THREAD

**Issue by Bob-Harper** [BlafKing/sd-civitai-browser-plus#25]
**Describe the bug**
When updating all models to retrieve tags for those that don't have them, it appears to be checking for info file as well as the valid models themselves.  Unless I am misinterpreting what I see.  Does the extension have a filter so it only looks at files with .safetensors etc?

**To Reproduce**
1. Go to CIvit AI tab
2. Go to 'Update All Tags' sub-tab
3. Click 'Update Selected Tags' (in my case I had Loras selected.  a second Update using Checkpoints had the same behaviour))
4. Look at console as it updates
5. See error

**Expected behavior**
Checking only valid filetypes, not including .txt, .info, .ini etcetera.  Assmuption is that would be easier on API by only searching valid filetypes.

**Screenshots/Example**

![image](https://github.com/BlafKing/sd-civitai-browser-plus/assets/114842939/b7f18474-a07e-4124-8214-996f15a55bc2)
![image](https://github.com/BlafKing/sd-civitai-browser-plus/assets/114842939/3a213c89-4bf8-4d4b-b139-2d3e7c512cf8)

copied text version: 
**Failed to fetch tags for C:\stable-diffusion\webui\models\Lora\desktop.ini
Failed to fetch tags for C:\stable-diffusion\webui\models\Lora\put_loras_here**

Failed to fetch tags for C:\stable-diffusion\webui\models\Lora\Artsy\line_girl.civitai.info
Tags saved as JSON in C:\stable-diffusion\webui\models\Lora\Artsy\line_girl.json
Failed to fetch tags for C:\stable-diffusion\webui\models\Lora\Artsy\lucyfleming-07.civitai.info
Tags saved as JSON in C:\stable-diffusion\webui\models\Lora\Artsy\lucyfleming-07.json
Failed to fetch tags for C:\stable-diffusion\webui\models\Lora\Artsy\meowhoodLora_v15.civitai.info
Request timed out for C:\stable-diffusion\webui\models\Lora\Artsy\meowhoodLora_v15.safetensors. Skipping...
Failed to fetch tags for C:\stable-diffusion\webui\models\Lora\Artsy\n3on - Style.civitai.info
Tags saved as JSON in C:\stable-diffusion\webui\models\Lora\Artsy\n3on - Style.json
Failed to fetch tags for C:\stable-diffusion\webui\models\Lora\Artsy\porcelainGzhel_v10black.civitai.info
Tags saved as JSON in C:\stable-diffusion\webui\models\Lora\Artsy\porcelainGzhel_v10black.json
Failed to fetch tags for C:\stable-diffusion\webui\models\Lora\Artsy\porcelainGzhel_v10white.civitai.info

**Additional context**
* Extension version: main 	c1b13e12 	2023-09-13 02:32:56
* OS: Windows 11
* SD version: A1111 version 1.6.0
* Python: 3.10.12

**Comment by BlafKing** [comment]
Thanks for the report!
I currently filter out invalid file types but it's a better idea to filter in valid filetypes to avoid filtering out any files I didn't account for.
I'll publish a fix in a bit that only scans certain file types instead of filtering out certain file types!

**Comment by BlafKing** [comment]
The extension has now been updated to hopefully fix this issue.
I've included a list of extensions which the extension uses to filter models it should scan being:
`['.pt', '.ckpt', '.pth', '.safetensors', '.th', '.zip', '.vae']`

Thanks for reporting the issue, it should now be fixed so I'll close this thread and mark it as resolved! :)

**Comment by Bob-Harper** [comment]
yow, that was quick :D  Well done, sir/ma'am/entity.  Glad it was an easy fix.
Looks like it's time for me to update!
