### ISSUE TITLE
[Bug]: model listing drops models on pagination

### ISSUE THREAD

**Issue by yetanotherCoriolis** [BlafKing/sd-civitai-browser-plus#254]
### Describe the bug.

When moving between pages of models, the first model on subsequent pages is missing, and perhaps from the first page as well.

### Steps to reproduce the problem.

Set tile count to 20.  Note the eleventh and twelfth models on the first page.
Set tile count to 10.  Note that the eleventh model does not appear at the start of the second page, but the twelfth.  The eleventh model is nowhere in the listing.

### Expected behavior

All models should show regardless of tile count.

### System info

* Extension version: 3,5,2
* OS: Windows 11
* SD-WebUI version: v1.8.0
* Python: 3.10.6

### Console logs

```Shell
no messages
```

### Additional information

I'm guessing that this is zero-bias problem from civitai's new cursor implementation, but who knows.

**Comment by BlafKing** [comment]
This issue has been fixed by the CivitAI team, I'll go ahead and close it 👍🏻

**Comment by yetanotherCoriolis** [comment]
Thank you!
