### ISSUE TITLE
[BUG] NameError: name 'aria2' is not defined

### ISSUE THREAD

**Issue by mikecastrodemaria** [BlafKing/sd-civitai-browser-plus#26]
**Describe the bug**
I receive this error message after installing the plugin :

*** Error loading script: civitai_gui.py
    Traceback (most recent call last):
      File "/.../modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/.../modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/.../extensions/sd-civitai-browser-plus/scripts/civitai_gui.py", line 7, in <module>
        import scripts.civitai_download as _download
      File "/.../extensions/sd-civitai-browser-plus/scripts/civitai_download.py", line 61, in <module>
        start_aria2_rpc(aria2)
    NameError: name 'aria2' is not defined

(/.../ replace the real path)

**To Reproduce**
install the extension, do a ./webui.sh on macM1

**Additional context**
app: stable-diffusion-webui.git
updated: 2023-08-31
hash: 5ef669de
url: https://github.com/AUTOMATIC1111/stable-diffusion-webui.git/tree/master

arch: arm64
cpu: arm
system: Darwin
release: 22.6.0
python: 3.10.6

xformers: 
diffusers: 0.16.1
transformers: 4.30.2

active: cpu
dtype: torch.float32
vae: torch.float32
unet: torch.float32

**Comment by mikecastrodemaria** [comment]
pip show aria2p   
Name: aria2p
Version: 0.11.3
Summary: Command-line tool and library to interact with an aria2c daemon process with JSON-RPC.
Home-page: 
Author: 
Author-email: Timothée Mazzucotelli <pawamoy@pm.me>
License: ISC
Location: /Volumes/SSD2TO/SD/venv/lib/python3.10/site-packages
Requires: appdirs, loguru, requests, toml, websocket-client
Required-by:

**Comment by James-Willer** [comment]
I think currently the extension does not support macOS

**Comment by BlafKing** [comment]
Thanks for notifying me about the issue!
Currently this extension does indeed not support MacOS since the Aria2 package for MacOS is not shipped with the extension.
I'll install MacOS on a VirtualBox to attempt to include Aria2 for MacOS, otherwise I'll adjust the extension so that it'll work on MacOS without Aria2. 👍🏻

**Comment by BlafKing** [comment]
I'm unfortunately unable to properly install a recent version of MacOS on my system so it's not possible for me to bug test any fixes.

I've updated the script and attempted a fix but again, can't bug test this so not sure if it will work.

Feel free to add me on Discord if you'd like to help me bug test!
tom_dom_

**Comment by derekslenk** [comment]
> I think currently the extension does not support macOS

This has very poor linux support in general. It assumes windows file pathing for everything '\'. You can't download models to subfolders.

I have aria2 installed but this newest version is trying to access a local executable, but using wrong paths:
`FileNotFoundError: [Errno 2] No such file or directory: '/extra/hdd1/sd/stable-diffusion-webui/extensions/sd-civitai-browser-plus/aria2/lin\\aria2c'`

**Comment by BlafKing** [comment]
I'm completely unfamiliar with anything outside Windows so thanks for bringing it to my attention, I'll change the way the path is written in a quick hotfix now!

**Comment by BlafKing** [comment]
I've made a quick fix that changes the path for just the aria2 initialization, I'll post a fix in a bit which changes all paths to use the correct pathing based on OS.

**Comment by derekslenk** [comment]
> I'm still very unfamiliar with anything outside Windows so thanks for bringing it to my attention, I'll change the way the path is written in a quick hotfix now!
> 
> I wasn't aware that Linux uses a different pathing '/' I'll use the OS check to alter the pathing
> 
> I've made a quick fix that changes the path for just the aria2 initialization, I'll post a fix in a bit which changes all paths to use the correct pathing based on OS.
> 
> In the future if an issue like this arises again please feel free to make a bug report so that I can fix it! :)

I suppose I could have tried a PR.

I assume you know, but python has built-ins for detecting the seperator. os.sep to see what it is, and you can use os.path.join to construct os agnostic paths

**Comment by BlafKing** [comment]
I'm still pretty new to Python and coding in general, so I still make silly mistakes like this way too often :,)
Thanks for pointing that out, I've just implemented a hotfix using those built-ins!

**Comment by derekslenk** [comment]
It's installing and starting for me again :) :+1:

**Comment by derekslenk** [comment]
Maybe i need to make a new bug for pathing. It's close, but its reading the OS dirs wrong now

![image](https://github.com/BlafKing/sd-civitai-browser-plus/assets/42957/64773b6d-faea-4e74-95d1-6f192a6e63f3)

If I select realistic, it actually creates a new folder called `'Stable-diffusion\realistic'` instead of the path `Stable-diffusion/realistic`
![image](https://github.com/BlafKing/sd-civitai-browser-plus/assets/42957/9dc6f3b8-a78a-4cf6-9a5c-6bb6f26b6985)

It creates the path appropriately with the folders named for the model
![image](https://github.com/BlafKing/sd-civitai-browser-plus/assets/42957/d3fb6ed6-02da-4d4b-a50d-8e59674cc472)

**Comment by BlafKing** [comment]
Thanks for letting me know!
The current error you're experiencing should now also be fixed 👍🏻 
I'll remove the posts from this thread about pathing issues to keep it on topic and I'll also double check if there are any other seperators which default to windows, if you find another error regarding pathing please make a new bug thread and I'll make sure to fix it!

**Comment by BlafKing** [comment]
Found the issue and it should now be fixed, like I said in the message above I'll remove the posts in this thread regarding pathing issues in a bit so that it stays on topic.
Hope you wont experience any issues anymore now! :)

**Comment by derekslenk** [comment]
Thank you very much!

**Comment by BlafKing** [comment]
Removed comments which were not relevant to this issue,
Please let me know if MacOS is still experiencing the issues you mentioned before!

**Comment by BlafKing** [comment]
Since the issue has been silent for 2 days, I'll go and close it.
If MacOS is still having issues, please feel free to open another bug report thread and I'll make sure to look into it! :)
