### ISSUE TITLE
[Bug]: NSFW Loras, Models, etc, do not update 

### ISSUE THREAD

**Issue by sirboblord** [BlafKing/sd-civitai-browser-plus#260]
### Describe the bug.

As the title says NSFW Loras, Checkpoints, embeddings and so on will not update previews tags or so on. I am on the most current version that being V 3.5.2, or on automatic 1111, 8d361ee0. However it does work with non NSFW models and such at least for me.  

### Steps to reproduce the problem.

1. download and install NSFW content and SFW content
2. update using the Browser plus options to do so 
3. refresh and observe 

### Expected behavior

SFW content will be downloaded as normal, while NSFW content is excluded. 

### System info

* Extension version: 8d361ee0.
* OS: windows 
* SD-WebUI version: Auto 1111 current version as of 4/2
* Python: 3.10.11

### Console logs

```Shell
No errors occurred
```

**Comment by BlafKing** [comment]
Thanks for reporting!

Will look into this 👍🏻

**Comment by BlafKing** [comment]
This should now be fixed in the latest version!

I'll mark this as resolved 👍🏻
