### ISSUE TITLE
[Bug]: HTML and api_info files saving in the wrong location

### ISSUE THREAD

**Issue by hakaserver** [BlafKing/sd-civitai-browser-plus#263]
### Describe the bug.

After latest bug fix, the HTML and api_info files are no longer saved in the same folder as the custom images location.
I have set a custom location for saving images and have both `Use sub folders inside custom images location` and `Store the HTML and api_info in the custom images location` options enabled (I also have both options of auto download images and model info enabled).

### Steps to reproduce the problem.

1. Have the settings described above enabled.
2. Download model, model info and images
3. HTML and api_info files are saved in the .safetensors file location, instead of the custom images location.

### Expected behavior

With the settings described and the commit 8585e67 it worked correctly, with the HTML and api_info files being saved in the correct location.
After updating to last commit 033ccc2 and without changing any settings, the HTML and api_info files are now being saved in the model location (along with the .safetensors file).

The images are still being saved in the correct location and the HTML file correctly look for them, but cant find them since they are in a different base folder (I also have the local images option enabled).

### System info

* Extension version: 033ccc2 
* OS: Win11
* SD-WebUI version: Forge (f0.0.17v1.8.0rc-latest-276-g29be1da7)
* Python: 3.10.6

### Console logs

```Shell
[NOTICE] Download complete: D:/SDWebui/stable-diffusion-webui/models/Lora/Subfolder/model.safetensors
CivitAI Browser+: Model saved to: D:\SDWebui\stable-diffusion-webui\models\Lora\Subfolder\model.safetensors
CivitAI Browser+: Model info saved to "D:\SDWebui\stable-diffusion-webui\models\Lora\Subfolder\model.safetensors.json"
CivitAI Browser+: Saved HTML to "D:\SDWebui\stable-diffusion-webui\models\Lora\Subfolder\model.safetensors.html"
CivitAI Browser+: Preview saved at "D:\SDWebui\stable-diffusion-webui\models\Lora\Subfolder\model.preview.png"
CivitAI Browser+: Downloaded sample_0.jpg
CivitAI Browser+: Downloaded sample_1.jpg```
```

### Additional information

The correct save location described in the console logs should have been `"D:\SDWebui\stable-diffusion-webui\models_db\Lora\Subfolder\"` for both 'Saved HTML and 'Model info', as per my configs.

**Comment by BlafKing** [comment]
Thanks for reporting!

The latest commit should fix this issue :)
I'll mark this as resolved as the issue should be fixed 👍🏻
