### ISSUE TITLE
[Bug]: non civitai models keeps getting processed every time.

### ISSUE THREAD

**Issue by silveroxides** [BlafKing/sd-civitai-browser-plus#265]
### Describe the bug.

Every time I want to update previews it processes models that has none even though it already was processed previously

### Steps to reproduce the problem.

1. Set up models without previews that are not on civitai
2. process them
3. do it again
4. notice that it keeps processing them even though they have previously been reported as not on civitai

### Expected behavior

Automatic exclusion of models not on civitai after first process

### System info

* Extension version: [8d361ee0](https://github.com/BlafKing/sd-civitai-browser-plus/commit/8d361ee085bc6b7700a6145eae41f08eb79498e4)
* OS: win11
* SD-WebUI version: 1.8.0
* Python: 3.10.9

### Console logs

```Shell
Just filled with bunch of requests anyway and not relevant.
```

**Comment by BlafKing** [comment]
Thanks for reporting!

This behavior was never implemented, kinda overlooked it 😅 
Latest commit now no longer scans any models that were previously not found

I'll mark this as resolved 👍🏻

**Comment by silveroxides** [comment]
> Thanks for reporting!
> 
> This behavior was never implemented, kinda overlooked it 😅 Latest commit now no longer scans any models that were previously not found
> 
> I'll mark this as resolved 👍🏻
@BlafKing 
I don't really feel like posting another bug report for what is pretty much identical issue. The same thing might be good to implement for the updating of model info and tags or maybe a checkbox for "update only new models info and tags"
