### ISSUE TITLE
[Bug]: Tags dont appear on prompt box

### ISSUE THREAD

**Issue by CesarCruzUtec** [BlafKing/sd-civitai-browser-plus#266]
### Describe the bug.

When downloading LoRas model it generates 5 files for each one: 2 json, 1 html, 1png, 1 safetensor. One of the json contains the modelId and sha256, and the other one contains the tags and description. When clicking in the lora to be used it should write the tags to the prompt box but onyl the lora name is used.
![image](https://github.com/BlafKing/sd-civitai-browser-plus/assets/67798431/d517d1e9-9a68-4508-8f3d-43a790075699)

### Steps to reproduce the problem.

1. Go to Civitai Browser +
2. Download any lora that contains tags
3. Click the lora on the extra networks tab

### Expected behavior

Tags should appear on the prompt

### System info

* Extension version: [033ccc27](https://github.com/BlafKing/sd-civitai-browser-plus/commit/033ccc27a1911119e61a4baf5118b6e2d46bae59)
* OS: Windows 11
* SD-WebUI version: [edd7bf7340](https://google.com/search?q=edd7bf7340a8415ded518aea97bb3bc027836c4bea117e95bba994c722302c7f) Fresh install
* Python: 3.10.11

### Console logs

```Shell
-
```

**Comment by BlafKing** [comment]
Thanks for reporting!

Latest commit should fix this issue
I'll mark this as resolved :) 👍🏻
