### ISSUE TITLE
[Bug]: extra "safetensors"suffix added to saved JSON filename

### ISSUE THREAD

**Issue by wangzan1990** [BlafKing/sd-civitai-browser-plus#267]
### Describe the bug.

When the model file is downloaded and the json file is saved, the filename of JSON file is added with the safetensors suffix.
e,g :
"xx.json" and "xx.safetensors.json" appeared in the same place.
Resulting in not being able to see the description on the checkpoints page

### Steps to reproduce the problem.

download a model

### Expected behavior

Could you please fix it?

### System info

* Extension version: 3.5.3
* OS: win11
* SD-WebUI version: 1.8.0
* Python: 3.10.11

### Console logs

```Shell
---
CivitAI Browser+: Model saved to: D:\sd-webui-aki\sd-webui-aki-v4.7\models\Stable-diffusion\realcartoonRealistic_v14.safetensors
CivitAI Browser+: Model info saved to "D:\sd-webui-aki\sd-webui-aki-v4.7\models\Stable-diffusion\realcartoonRealistic_v14.safetensors.json"
CivitAI Browser+: Saved HTML to "D:\sd-webui-aki\sd-webui-aki-v4.7\models\Stable-diffusion\realcartoonRealistic_v14.safetensors.html"
CivitAI Browser+: Preview saved at "D:\sd-webui-aki\sd-webui-aki-v4.7\models\Stable-diffusion\realcartoonRealistic_v14.preview.png"
```

**Comment by BlafKing** [comment]
Thanks for reporting!

This should now be fixed in the latest commit!
I'll mark this as resolved 👍🏻
