### ISSUE TITLE
[Bug or not?]: can't save image, when i use proxy(socks5://myproxyip:myproxyport).

### ISSUE THREAD

**Issue by larchsis** [BlafKing/sd-civitai-browser-plus#268]
### Describe the bug.

Proxy options -> Proxy address -> socks5://myproxyip:myproxyport
custom save image path -> keep empty
search model, save info, download model is ok.
1. press [save image] in brower tab, there is nothing in my folder.
2. some model has more than 10 example image, i can only see 10, why?

### Steps to reproduce the problem.

1. Go to brower tab
2. Press [save image] button
3. nothing in my folder.

### Expected behavior

Proxy options -> Proxy address -> socks5://myproxyip:myproxyport
custom save image path -> keep empty
search model, save info, download model is ok.
1. press [save image] in brower tab, there is nothing in my folder.
2. some model has more than 10 example image, i can only see 10, why?

### System info

* Extension version: d8738a5 and before
* OS: Windows 11
* SD-WebUI version: v1.8.0
* Python: 3.10.11

### Console logs

```Shell
CivitAI Browser+: Error: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
CivitAI Browser+: Error: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
CivitAI Browser+: Error: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
```

**Comment by BlafKing** [comment]
Thanks for reporting!

I'll see if I can re-create the issue!

**Comment by BlafKing** [comment]
Sorry for getting back so late, I was unfortunately not able to re-create the issue.

I'm assuming CivitAI somehow blocks the connection when connected from the proxy, I can't really tell you why :/
I'll close this as can't fix, hope you can find a solution though! but don't think I can do anything from within the extension.
