### ISSUE TITLE
471749[Bug]: Python module 'fake_useragent' has not been imported correctly, please try to restart or install it manually.

### ISSUE THREAD

**Issue by larinius** [BlafKing/sd-civitai-browser-plus#274]
### Describe the bug.

CivitAI Browser+: Python module 'fake_useragent' has not been imported correctly, please try to restart or install it manually.
CivitAI Browser+: Python module 'ZipUnicode' has not been imported correctly, please try to restart or install it manually.
CivitAI Browser+: Aria2 RPC restarted
CivitAI Browser+: Python module 'fake_useragent' has not been imported correctly, please try to restart or install it manually.
CivitAI Browser+: Python module 'ZipUnicode' has not been imported correctly, please try to restart or install it manually.
CivitAI Browser+: Aria2 RPC restarted

### Steps to reproduce the problem.

Just use it normally

### Expected behavior

fix it already!!!!!

### System info

Google colab

### Console logs

```Shell
ivitAI Browser+: Python module 'fake_useragent' has not been imported correctly, please try to restart or install it manually.
CivitAI Browser+: Python module 'ZipUnicode' has not been imported correctly, please try to restart or install it manually.
CivitAI Browser+: Aria2 RPC restarted
CivitAI Browser+: Python module 'fake_useragent' has not been imported correctly, please try to restart or install it manually.
CivitAI Browser+: Python module 'ZipUnicode' has not been imported correctly, please try to restart or install it manually.
CivitAI Browser+: Aria2 RPC restarted
```

**Comment by larinius** [comment]
Just open your repo and edit requirerments.txt, how many users must bug you to do that?

**Comment by BlafKing** [comment]
No need to be so toxic about it.

Most SD-WebUI extensions do not use requirements.txt but instead use the `install.py` file, which gets used by SD-WebUI automatically to install these packages as long as the `--skip-install` command line is not used.

It might not work on some web hosts, like Google or runpod, as I've not tested those.

Regardless, you can fix these by installing the required packages manually.

You should be able to install them by doing
```
pip install fake-useragent
pip install ZipUnicode
```

I'll include a requirements.txt as well with all the required packages, but again, this shouldn't be required afaik when using the extension in SD-WebUI.
