### ISSUE TITLE
[Bug]: Drives other than C: break

### ISSUE THREAD

**Issue by ice-fly** [BlafKing/sd-civitai-browser-plus#276]
### Describe the bug.

Running update tags breaks when path is on D:

### Steps to reproduce the problem.

Install on another drive and try to update tags

### Expected behavior

Saves tags to any drive path

### System info

* Extension version:[d8738a5f](https://github.com/BlafKing/sd-civitai-browser-plus/commit/d8738a5f40d1097f45e5e1b227d813ac75dfd80f)
* OS: Windows 10 64
* SD-WebUI version:version: [v1.9.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/adadb4e3c7382bf3e4f7519126cd6c70f4f8557b)  •  python: 3.10.6  •  torch: 2.1.2+cu121  •  xformers: 0.0.23.post1  •  gradio: 3.41.2  •  checkpoint: [152bafff28](https://google.com/search?q=152bafff28930166198794346bdf6ea8b55ec1482fdac748151e20b0b598c4cc)
* Python:3.10.6  

### Console logs

```Shell
save_path, name = get_save_path_and_name(install_path, file_name, api_response)
  File "D:\Downloads\Installs\sdwebui\webui\extensions\sd-civitai-browser-plus\scripts\civitai_file_manage.py", line 814, in get_save_path_and_name
    sub_folder = os.path.normpath(os.path.relpath(install_path, gl.main_folder))
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 744, in relpath
    raise ValueError("path is on mount %r, start on mount %r" % (
ValueError: path is on mount 'D:', start on mount 'C:'
```

### Additional information

Used to work

**Comment by ice-fly** [comment]
Duplicates #271

**Comment by slaw** [comment]
Duplicate #271 resolution is based on symlinks on windows. 
I am on windows, but I don't use symlinks to link model folders to Forge or a1111.
In the .bat file you can set custom paths in the COMMANDLINE_ARGS.
For example, if you have your models on a D drive: 

set COMMANDLINE_ARGS=--xformers  --theme dark  ^
 --ckpt-dir 'D:\My Models\Stable-diffusion-models' ^
 --embeddings-dir 'D:\My Models\embeddings' ^
 --hypernetwork-dir 'D:\My Models\hypernetworks' ^
 --vae-dir 'D:\My Models\VAE' ^
 --lora-dir 'D:\My Models\Lora' ^
 --lyco-dir 'D:\My Models\LyCORIS' ^
 --esrgan-models-path 'D:\My Models\ESRGAN'

You can even add a custom path to controlnet models, but you need the controlnet extension installed first or Stable Diffusion throws errors.

 --controlnet-dir 'D:\My Models\ControlNet'
 
 Recently I have encountered the OP's issue when trying to update any of the models.
``` ValueError: path is on mount 'D:', start on mount 'C:' ```
