### ISSUE TITLE
[Bug]: Stopped working as intended

### ISSUE THREAD

**Issue by CoddedApple** [BlafKing/sd-civitai-browser-plus#277]
### Describe the bug.

Open the extention and it just doesn't work, images below show everything.
The console doesn't give any errors and only mentions `CivitAI Browser+: Aria2 RPC started` in regards to the ext.
I've tried on v1.7.0 and v1.9.0 of the webui with the same result, both versions I also disabled other extensions with the same result. I've tried reinstalling too.
Strange thing is before it became like this it worked fine and then ten hours later it just didn't, nothing was updated, I was using 1.7.0, I never closed the webui, I just left it idle doing nothing and when I came back, the next time I used the extention it just became like this. Been stuck like this for the past few weeks and updates haven't fixed the issue.

![1](https://github.com/BlafKing/sd-civitai-browser-plus/assets/151252365/2eb6e8a3-9495-492b-bf78-8a85ab269d65)
![2](https://github.com/BlafKing/sd-civitai-browser-plus/assets/151252365/9cae5619-1e74-46b1-88c1-87d664a92050)
![3](https://github.com/BlafKing/sd-civitai-browser-plus/assets/151252365/a35bb2ef-0102-48b4-99c5-b65ff0fd60f1)
![4](https://github.com/BlafKing/sd-civitai-browser-plus/assets/151252365/57400037-ad9e-4465-8c85-8bee6c029c7e)
![5](https://github.com/BlafKing/sd-civitai-browser-plus/assets/151252365/cfb8d2aa-d00e-41f4-a60d-97f9431aa3f8)

Also the images aren't clickable, the model dropdown is the only way to select which doesn't do anything else such as load model info in other dropdowns or enable download button.

### Steps to reproduce the problem.

Nothing, it defalts to this.

### Expected behavior

A grid array of models to choose from with clickable images that load the model info ready for downloading.

### System info

* Extension version: [d8738a5f](https://github.com/BlafKing/sd-civitai-browser-plus/commit/d8738a5f40d1097f45e5e1b227d813ac75dfd80f)
* OS: Win10
* SD-WebUI version: v1.7.0 & 1.9.0
* Python: 3.10.11

### Console logs

```Shell
Not Applicable
```

**Comment by BlafKing** [comment]
Sorry for the delayed response! been really busy with work lately :,)

As far as I can tell, it looks like the css/javascript code has stopped working for the extension, which is causing the weird/broken display.

Could you try to access the browser console to see if that's logging any errors related to the extension?
Unfortunately hard to pinpoint what the issue could be without any error logs :,)

**Comment by CoddedApple** [comment]
@BlafKing Thank you for suggesting to check the console, I never even considered checking it. Apparently it's something on my end that is the problem and not the extention itself, in the console there's a bunch of `net::ERR_ABORTED 403 (Forbidden)` errors for multiple extensions, some of which also have their own issues and now I know why.

Don't know what's causing the 403 error so still gotta figure that out though. If you have any suggestions I'd be grateful but otherwise can probably close the bug report as the 403 error effects the other extensions even when cb+ is disabled.

**Comment by BlafKing** [comment]
Awesome, glad you managed to fix it!
