### ISSUE TITLE
[Bug]: Setting Custom save images location breaks Use local HTML file for model info when Use local images in the HTML is enabled.

### ISSUE THREAD

**Issue by jackminghaoxu** [BlafKing/sd-civitai-browser-plus#287]
### Describe the bug.

Locally saved html files do not load locally save images when Custom save images location is set and Use local HTML file for model info when Use local images in the HTML are enabled.

### Steps to reproduce the problem.

Assuming stable-diffusion-webui is installed to F:\stable-diffusion-webui-1.9.3, and running Microsoft Edge on Windows 10,
1. Check Use local HTML file checkbox for model info in CivitAI Browser+ Browser settings.
2. Check Use local images in the HTML checkbox in CivitAI Browser+ Browser settings.
3. Set Custom save images location field to civitaibrowser\saveme in CivitAI Browser+ Browser settings.
4. Check Automatically save all images checkbox in CivitAI Browser+ Downloads settings.
5. Apply settings.
6. Download model EasyNegative as easynegative.safetensors to F:\stable-diffusion-webui-1.9.3\embeddings
7. Open F:/stable-diffusion-webui-1.9.3/embeddings/easynegative.html in Microsoft Edge.
Images are broken, opening their link in a new tab brings up F:/stable-diffusion-webui-1.9.3/embeddings/easynegative_0.jpg, which doesn't exist.

### Expected behavior

The html file should be trying to open F:/stable-diffusion-webui-1.9.3/civitaibrowser/saveme/easynegative_0.jpg.

### System info

* Extension version: [5ab99d58](https://github.com/BlafKing/sd-civitai-browser-plus/commit/5ab99d589a1f816f49410d8a721cb7fa79135d80) 2024-05-21 22:00:11
* OS: Windows 10 22H2
* SD-WebUI version: 1.9.3
* Python: 3.10.6

### Console logs

```Shell
n/a
```

### Additional information

Html files are also broken if Store the HTML and api_info in the custom images location is enabled. The html file saves images as civitaibrowser\saveme\easynegative_0.jpg. Trying to open the link brings up F:/stable-diffusion-webui-1.9.3/civitaibrowser/saveme/civitaibrowser/saveme/easynegative_0.jpg.

**Comment by BlafKing** [comment]
This should now (finally) be fixed in the latest version!
Apologies it took so long 😅 

I'll mark this as resolved 👍🏻
