### ISSUE TITLE
Feature Request: Date Display

### ISSUE THREAD

**Issue by ManOrMonster** [BlafKing/sd-civitai-browser-plus#3]
**Issue**: While browsing by Newest on a selection other than "Today", it would be helpful to know when models were posted.

**Solution**: A divider between thumbnail rows that displays the current date of all thumbnails in the following rows. For instance, browsing by "Newest" and by "Month", every thumbnail that was posted on 8-28-2023 would be grouped together under a divider that says "8-28-2023--------------------------------------------" or something similar. Then the next day's thumbnails would be displayed under a similar divider, and so on.

`item["createdAt"]`

**Comment by BlafKing** [comment]
Sounds like a good request to me, I'll see if I can implement this.

I'll probably make it a toggleable feature since I'd personally find it a bit obnoxious to have the dates above tiles so it'll be an optional feature which you can toggle on/off! :)

**Comment by ManOrMonster** [comment]
Just a quick mockup of what I was thinking:

Group by date:
<img width="757" alt="image" src="https://github.com/BlafKing/sd-civitai-browser-plus/assets/3925151/44b376c0-5dea-4e40-92d9-916195f81242">

Another option would be to just display the date below each thumbnail, would be less obtrusive:

<img width="145" alt="image" src="https://github.com/BlafKing/sd-civitai-browser-plus/assets/3925151/360d7c76-70b8-49fa-b183-3d702dc931c7">

**Comment by BlafKing** [comment]
A new toggle has been added to allow filtering cards like you're first example showed, thanks for the suggestions and I hope you can enjoy the script even more now! :)
I'll go ahead and close this thread since the requested features have been implemented!
