### ISSUE TITLE
[BUG] Major issue - Deleting a model deletes ALL models with same characters in name!

### ISSUE THREAD

**Issue by jwvanderbeck** [BlafKing/sd-civitai-browser-plus#30]
**Describe the bug**
I deleted the "RPG" model, and it deleted EVERY model I had (including all my custom models) with "RPG" in the name

**To Reproduce**
1. Select a model you already have, and one that has a name present in other models
2. Click on Delete Model

**Expected behavior**
Only the actual selected model should be deleted, not every model that contains its name - such as custom mixes which by default A1111 names with the model names used in the mix

**Screenshots**

**Additional context**
* Extension version: https://github.com/BlafKing/sd-civitai-browser-plus/commit/f9e980bdcd342bf9969a5dd6459d95ee8a5cb262
* OS: Windows 11
* SD version: 5ef669de080814067961f28357256e8fe27544f4 (1.6.0)

Removed: E:\stable-diffusion-webui\models\Stable-diffusion\0.7(protogenX53Photorealism_10) + 0.3(rpg_V4).civitai.info
Removed: E:\stable-diffusion-webui\models\Stable-diffusion\0.7(protogenX53Photorealism_10) + 0.3(rpg_V4).safetensors
Removed: E:\stable-diffusion-webui\models\Stable-diffusion\rpg_V4 + 0.2(duchaitenaiart_V20 - SD-mode-1.5l) + 0.1(inkpunkDiffusion_v2 - SD-mode-1.5l).civitai.info
Removed: E:\stable-diffusion-webui\models\Stable-diffusion\rpg_V4 + 0.2(duchaitenaiart_V20 - SD-mode-1.5l) + 0.1(inkpunkDiffusion_v2 - SD-mode-1.5l).safetensors
Removed: E:\stable-diffusion-webui\models\Stable-diffusion\rpg_V4 + 0.2(duchaitenaiart_V20 - SD-mode-1.5l) + 0.2(inkpunkDiffusion_v2 - SD-mode-1.5l).civitai.info
Removed: E:\stable-diffusion-webui\models\Stable-diffusion\rpg_V4 + 0.2(duchaitenaiart_V20 - SD-mode-1.5l) + 0.2(inkpunkDiffusion_v2 - SD-mode-1.5l).safetensors
Removed: E:\stable-diffusion-webui\models\Stable-diffusion\rpg_V4 + 0.2(duchaitenaiart_V20 - SD-mode-1.5l) + 0.2(xperoEnd1essModel_v1 - SD-mode-1.5l).civitai.info
Removed: E:\stable-diffusion-webui\models\Stable-diffusion\rpg_V4 + 0.2(duchaitenaiart_V20 - SD-mode-1.5l) + 0.2(xperoEnd1essModel_v1 - SD-mode-1.5l).ckpt
Removed: E:\stable-diffusion-webui\models\Stable-diffusion\rpg_V4 + 0.2(duchaitenaiart_V20 - SD-mode-1.5l) + 0.4(inkpunkDiffusion_v2 - SD-mode-1.5l).civitai.info
Removed: E:\stable-diffusion-webui\models\Stable-diffusion\rpg_V4 + 0.2(duchaitenaiart_V20 - SD-mode-1.5l) + 0.4(inkpunkDiffusion_v2 - SD-mode-1.5l).safetensors
Removed: E:\stable-diffusion-webui\models\Stable-diffusion\rpg_V4 + 0.2(duchaitenaiart_V20 - SD-mode-1.5l).civitai.info
Removed: E:\stable-diffusion-webui\models\Stable-diffusion\rpg_V4 + 0.2(duchaitenaiart_V20 - SD-mode-1.5l).safetensors
Removed: E:\stable-diffusion-webui\models\Stable-diffusion\rpg_V4.civitai.info
Removed: E:\stable-diffusion-webui\models\Stable-diffusion\rpg_V4.preview.png
Removed: E:\stable-diffusion-webui\models\Stable-diffusion\rpg_V4.safetensors

**Comment by BlafKing** [comment]
I'm very sorry to hear this sad news, there was already a bug report about a similair issue and it has already been fixed in the latest version, this error should no longer happen in the latest version.
Bug report about same issue: https://github.com/BlafKing/sd-civitai-browser-plus/issues/29

I'm very sorry to hear you've lost all your files I went to fix this error as soon as I could yesterday when another user reported it.
In the latest version, models get put into the Trash instead of completely deleted and there are additional checks to make sure this cannot happen anymore.

Again very sorry to hear you've lost all your files :(
Please make sure to update to the latest version so this cannot happen again!

**Comment by jwvanderbeck** [comment]
I didn't realize (or expect) there was a new version since I only
downloaded this last night haha

- John Vanderbeck
- http://www.johnvanderbeck.com
