### ISSUE TITLE
[Bug]: Search result nth +1 tile is not displayed

### ISSUE THREAD

**Issue by ibuki110** [BlafKing/sd-civitai-browser-plus#302]
### Describe the bug.

When searching with a tile count of 100, the second page is displayed starting with the 102nd tile, so it appears that the 101st tile is not displayed in the search results.
The same behavior appeared to occur when the tile count was changed. 
Thanks for confirming.

*Translated from Japanese at DeepL

### Steps to reproduce the problem.

Search type:Model name
content type:
base model:Pony
Time period:All Time
Sort by:Newest
Save int after download:☑true
NSFW content:☑true
Divide cards by date:□false
Liked models onry:□false
Hide installed models:□false
Tile size:20
Tile count:16

### Expected behavior

Show search result nth +1

### System info

* Extension version:0b97a482
* OS:win11 23H2
* SD-WebUI version:[f0.0.17v1.8.0rc-latest-276-g29be1da7]
* Python:3.10.6

### Console logs

```Shell
N/A
```

**Comment by yetanotherCoriolis** [comment]
I'm not the developer, but this appears to be an old bug over on CivitAI that they closed without fixing.  I suggest you also report it there.

**Comment by ibuki110** [comment]
Are you saying that it is a bug in the API provided? 
I don't know where I can help, but let me know if there is anything I can do to help. Thanks for letting me know!
提供されたAPIのバグということですか？
どこでお手伝いできるかわかりませんが、何かできることがあれば教えてください。教えてくれてありがとう！

**Comment by BlafKing** [comment]
This is unfortunately not something that can be fixed on my end, as this is the direct result of an error with the CivitAI API, there seems to be an existing bug report on CivitAI: https://github.com/civitai/civitai/issues/1372

I will close this and mark it as cannot fix, as I unfortunately cannot fix this.
