### ISSUE TITLE
[Bug]: meta data dont appear

### ISSUE THREAD

**Issue by ZampolitGL** [BlafKing/sd-civitai-browser-plus#313]
### Describe the bug.

I apologize in advance for my bad English.
I installed the module on fresh SD (because I haven't updated SD for a loooooong time dowanload a new one was better option) . As a result, now the extension does not show meta data and there is no "send to txt2img" button.
![Снимок экрана 2024-07-26 175421](https://github.com/user-attachments/assets/0cd265a5-32a8-47b7-8e79-9bf00e9ffbd4)
![Снимок экрана 2024-07-26 171706](https://github.com/user-attachments/assets/b75527c6-ca45-4c20-bd34-7a3eee947786)
![Снимок экрана 2024-07-26 171625](https://github.com/user-attachments/assets/e010e27d-c814-485a-ab2d-c60a621f4f97)

### Steps to reproduce the problem.

1. Go to lora or etc tabs/ browser-plus tab
2. Press civitai icon/lora
3. A window opens with pictures, description, links, but there is no field with meta data and "send to txt2img" button.

### Expected behavior

reappear of meta-data

### System info

* Extension version: 0b97a48
* OS: Win 10,
* SD-WebUI version: 1.9.4 
* Python: 3.10.10 

### Console logs

```Shell
no error logs when try to see meta data.
```

**Comment by Pemmican6** [comment]
Seems like the Api no longer returns the metadata for the images in the model rest service.
however the image service still does.  
I was able to call the image service with the model id and take the resultant data and use it to get the images and prompts.
One weirdness - the model api returned 9 images, but the image api only returned 4, not sure about that.

**Comment by atmogenic** [comment]
oh so it's not just me, i updated today and noticed that the icons for the filter and search are broken and then there was no data for the prompts to "send to txt2img"

**Comment by fiyota** [comment]
I've noticed this as well, it seems the recent update to the web UI broke a few features. I can't scroll to the next page of results, downloads seem to not show their status correctly and images in the UI are broken as well.

**Comment by Sicnics** [comment]
This was broken for a few days however appears to be working again for me

**Comment by fiyota** [comment]
I'm using Forge with the latest version of both Forge and CivitAI Browser and it's still broken. Are you using Automatic1111?
