### ISSUE TITLE
[Bug]: Extension causing JavaScript Error Loop

### ISSUE THREAD

**Issue by Corn0nTheRob** [BlafKing/sd-civitai-browser-plus#316]
### Describe the bug.

Having the extension enabled on SD Forge with gradio 4.4.0 or later causes the JavaScript to endlessly generate the warning:
Too many arguments provided for the endpoint. 
Over time, this causes the application to slow down until you either a) clear JS console or b) disable the extension.

### Steps to reproduce the problem.

Occurs on any page of the WebUI.

### Expected behavior

Warnings should not be generated infinitely.

### System info

Any SD Forge version after 07/28/2024

### Console logs

```Shell
9
index.js:462 Too many arguments provided for the endpoint.
Rt	@	index.js:462
```

**Comment by BlafKing** [comment]
Thanks for reporting!

The error should now no longer loop indefinitely since #341, it can still occur on certain actions which I'm still looking into, but it won't loop anymore!

I'll mark this as resolved 👍🏻
