### ISSUE TITLE
[Bug]: When downloading a model that has either a non supported windows character in the title or version name, extension will not be able to download

### ISSUE THREAD

**Issue by Lumerica** [BlafKing/sd-civitai-browser-plus#322]
### Describe the bug.

On windows,
If you use the option to create folders based on Model Name and also Model version this bug gets triggered if a model has a non supported windows character as filename/foldername.

Example
When downloading a checkpoint or lora and the title of the model ends with a Space, This will result in an error as it cannot be downloaded.
the extension can create the folder but on windows the last space will be removed whilst the extension insist to navigate to the created folder with a space behind.
Error results in like the following example:
N:/GIT/stable-diffusion-webui/models/Lora/Other/SD 1.5/aDDont/{DD} Usefull stuff&scripts I use to make Loras /v1.0, cause: No such file or directory
Ps I remember seeing titles having a space as first character last year, so this will also trigger a failure of downloading. Thus same condition would apply that the download will.
Another example you can test yourself (its not a lora but an article, but allows you to trigger this behavior of the handling in the extension. Honestly Imo civitai should have handled these leading space or title that might start with a space.):
https://civitai.com/models/67857

Same applies to a model version name. if the model version name contains a non supported character or a space at the end, this same issue applies. For example I noticed some creators using the pipe ( " | ") character or the greater and smaller than character (" <> ") as version name. This will break the folder creation and sometimes even the download because the problem gets shifted to filename

### Steps to reproduce the problem.

1. Enable the option to create folder using this template [\Base model\Author name\Model name\Model version]
2.  Go to Search for this model in the extension (https://civitai.com/models/67857)
2. The subfolder the extension suggest to create would be this:
"Other/SD 1.5/aDDont/{DD} Usefull stuff&scripts I use to make Loras /v1.0"
4. Notice the leading space at the end of the model name before the version name. This will make windows create the folder until the folder name, but the extension cannot proceed to create model version folder v1.0, because it cannot find the folder for the model name that ends with a space.

### Expected behavior

Purge any non supported characters whether its a space at the end or in front.

### System info

* Extension version: I think its version 3.5.3? my SD automatic 1111 says version [0b97a482](https://github.com/BlafKing/sd-civitai-browser-plus/commit/0b97a482ad4e3c0fec797a797414a0f0eeef08fa)
* OS: 10
* SD-WebUI version: 1.10.1
* Python: 3.10.10

### Console logs

```Shell
I guess the description is clear enough, I have already manually downloaded the models. in case needed I will delete and redownload just for the console log to be shared.
```

**Comment by Lumerica** [comment]
solved it mostly by modifying the code but it still cannot deal with version names, especially Pipe character

**Comment by Lumerica** [comment]
Update: Solved the problem to deal with Model name sub folder as well as model version name sub folder creation. This latter somehow cannot be cleaned with the Regex cleaned_name. Thus I had to use replace after many tries.

https://github.com/Lumerica/sd-civitai-browser-plus_fix/commit/af79e99046cc8529f991f1de7df2f67fd99e2641

Note, please review this change above. I have no idea how github works, so I also do not know how to get these changes to your github, I had to learn python but also setting these fork repository github things.

(apart from my folder structure changes, I just had them already changed for my own use prior attempting to fix that). I'm not a python developer as mentioned above. So the code could use some rewrite, but it works at least and solves the struggle when dealing with civitai users using strange character names or accident double/trailing space.

**Comment by Lumerica** [comment]
I made some more changes to the codes and it did not allow me to send a pull request so I had to close previous... No idea why github didnt allow me.

new request that includes this fix is:
https://github.com/BlafKing/sd-civitai-browser-plus/pull/343

**Comment by BlafKing** [comment]
The issues you mentioned should now be fixed in the latest version!

I'll mark this as resolved, but please feel free to let me know if you still experience any issues 👍🏻
