### ISSUE TITLE
[Bug]: Laggy UI (Forge Gradio 4+)

### ISSUE THREAD

**Issue by younyokel** [BlafKing/sd-civitai-browser-plus#326]
### Describe the bug.

The entire user interface in Forge is now slow to respond to user input compared to versions prior to Gradio 4

### Steps to reproduce the problem.

1. Compare performance with and without CivitAI Browser+

### Expected behavior

--

### System info

* Extension version: latest
* OS: Windows 10
* SD-WebUI version: [96f264e](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/96f264ec6a8829cac9a12c9a75b5e8fa1e363a45)
* Python: 3.10.11

### Console logs

```Shell
--
```

**Comment by nor1c** [comment]
any update?

**Comment by Terroosh** [comment]
> any update?

There hasn't been an update in 3 months. BlafKing might be busy or could have moved on from this project.

**Comment by KuroNeko87** [comment]
Yeah, experiencing same issue. Feels like using browser when cpu/ram is at 100% but it isn't.

**Comment by crsongbird** [comment]
It maxes out one core of the CPU for some reason.

**Comment by metapea** [comment]
it's been also laggy on reforge for a while

**Comment by Nisekoi-1** [comment]
same

**Comment by BenjaminSymons** [comment]
I've remedied the initial lag causing code in my fork and pull request here: https://github.com/BlafKing/sd-civitai-browser-plus/pull/339

Additional work is needed to remove the calls to tabs that are no longer considered tabs and commences a similar endpoint spam

**Comment by younyokel** [comment]
#339

**Comment by younyokel** [comment]
@BenjaminSymons I tried your fork. It seems to be less laggy compared to this version, but still lags a bit

**Comment by prezofpizza** [comment]
@BenjaminSymons I seem to get stock with the "Loading model info, please wait!" model and can't seem to figure out why.  Only happens in Forge, Auto1111 is fine.  Used console logs to check that parameters are set correctly, so not sure what could be causing the issue.

Has anyone else run into this?

**Comment by younyokel** [comment]
no way, seems to be fixed now

Can more people confirm

**Comment by BlafKing** [comment]
Should indeed be mostly fixed!
Just merged the pull request #341 which contained code from @BenjaminSymons and @channelcat so you can all thank them for the initial fix! 🎉

I'm getting back into maintaining this project so I'll try my best to find the time to patch things up further wherever the issues still exist! (plenty of bugs left to catch 👀)

There are currently still a few performance issues left, so I'll try my best to find ways to optimise things further!

This issue should (mostly) be fixed now though, at least till the point where the UI doesn't become unusable anymore 😅
So I'll close this issue!
