### ISSUE TITLE
[Bug]: icons missing from gui

### ISSUE THREAD

**Issue by lgwjames** [BlafKing/sd-civitai-browser-plus#334]
### Describe the bug.

i was using for weeks ok when using SD. Now using via forge and the icons for arrows etc are missing. I removed folder, tried to reinstall and the same

### Steps to reproduce the problem.

1. Go to .... your sd forge gui
2. Press .... -civitai-browser-plus 
3. .look at the icons
![Screenshot 2024-09-07 at 09-15-43 Stable Diffusion](https://github.com/user-attachments/assets/a41a479b-21c2-422c-a349-f58ed5213c60)

### Expected behavior

used to have clear icons and arrows

### System info

* Extension version:
* OS: windows 11
* SD-WebUI version: version: [f2.0.1v1.10.1-previous-506-gd1e40361](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/d1e403619dd6a9570052c1e99869fd108f071a72)
* Python: 3.10.6

### Console logs

```Shell
wont show a error
```

**Comment by randomerrorgenerator** [comment]
it seems to be a forge thing, works ok in a1111. not sure how to fix it for ya though

**Comment by BlafKing** [comment]
Should now be fixed in the latest version, thanks for reporting!

Closed and marked as solved 👍🏻
