### ISSUE TITLE
[Bug]: Flux support?

### ISSUE THREAD

**Issue by onyxlee** [BlafKing/sd-civitai-browser-plus#335]
### Describe the bug.

This extension seems to be not getting any updates for a few months. Could you add a category in the drop down filter to allow us to search Flux related content? Thanks a lot!

### Steps to reproduce the problem.

1. Go to dropdown filter
2. Press base model
3. No flux category

### Expected behavior

More categories to reflect recent SD development.

### System info

* Extension version:
* OS:
* SD-WebUI version:
* Python:

### Console logs

```Shell
N/A
```

**Comment by Natans8** [comment]
There's already a [pull request](#333) for this issue. But it would be good to make the filter list update automatically with new models added to CivitAI almost on a monthly basis now.

**Comment by onyxlee** [comment]
Thank you, I second that. It would be amazing if this could be done automatically.

**Comment by alfonslm** [comment]
You should be able to copy paste the 1 change by hand in the meanwhile.

Just open the pull request and replace that line 188 for the civitai_gui.py file with a script editor eg Visual Studio Code

https://github.com/BlafKing/sd-civitai-browser-plus/pull/333/files
https://code.visualstudio.com/Download

@Natans8 thanks for mentioning that some one have alredy made the fix

**Comment by schoenid** [comment]
> Just open the pull request and replace that line 188 for the civitai_gui.py file 

Works well on the local file.
Thanks!

**Comment by BlafKing** [comment]
Has been fixed as #333 is now merged, thanks for reporting!

I'll close this report and mark it as solved 👍🏻
