### ISSUE TITLE
[Bug]: Compatibility issues with Forge WebUI

### ISSUE THREAD

**Issue by ryankhart** [BlafKing/sd-civitai-browser-plus#338]
### Describe the bug.

I've pinpointed this issue reported over on the Forge WebUI repo as being linked with this extension. As soon as I uninstalled this extension the issues went away.

https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/1815

Summary:
- NaN shows up when adjusting token/LoRA strength with Ctrl+Arrow keys
- Clicking on the generated images (at least in the txt2img tab) does not load the full page image viewer.

### Steps to reproduce the problem.

1. Install this extension of Forge WebUI
2. Move the typing cursor over a word or a group of words already with a custom strength value (i.e. "(bokeh:0.6)")
3. Press ctrl+up or ctrl+down

### Expected behavior

Pressing ctrl+up or ctrl+down should cycle through the strength levels in steps of 0.1 (or 0.05 for loras) by default.

Instead, it replaces anything that already has a custom strength with "NaN", and for anything that doesn't already have a custom strength, it does what ctrl+up or ctrl+down does in a textbox on any web page.

### System info

* Extension version: https://github.com/BlafKing/sd-civitai-browser-plus/commit/0b97a482ad4e3c0fec797a797414a0f0eeef08fa
* OS: Windows 11
* SD-WebUI version: https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/b20cb4bf0e526f890fcd40a4d039da581cfebafa
* Python: 3.10.6

### Console logs

```Shell
Nothing notable or different shows up in the console than when it worked before.
```

**Comment by prezofpizza** [comment]
Just adding that I'm having the same issue with Forge, even after the latest update.

**Comment by ryankhart** [comment]
No longer an issue. Either one of the commits here or with Forge fixed this, but it's working as intended again.
