### ISSUE TITLE
[Bug]:There is a problem Loading model info

### ISSUE THREAD

**Issue by aigoar** [BlafKing/sd-civitai-browser-plus#347]
### Describe the bug.

There is a problem while Loading model info, when I click on lora  it stays stuck and does not give you any information about the model

### Steps to reproduce the problem.

1. Go to lora model
2. Press civitai logo

### Expected behavior

![لقطة الشاشة 2024-10-13 190329](https://github.com/user-attachments/assets/17b12906-fc40-4abc-9cea-81ad4d04d03f)

### System info

* Extension version:
* OS:
* SD-WebUI version:
* Python:

### Console logs

```Shell
[Unload] Trying to free 8158.16 MB for cuda:0 with 0 models keep loaded ... Current free memory is 9227.30 MB ... Done.
[Memory Management] Target: KModel, Free GPU: 9227.30 MB, Model Require: 4897.05 MB, Previously Loaded: 0.00 MB, Inference Require: 0.00 MB, Remaining: 4330.25 MB, All loaded to GPU.
Moving model(s) has taken 1.15 seconds
100%|##################################################################################| 30/30 [00:29<00:00,  1.00it/s]
[Unload] Trying to free 5955.47 MB for cuda:0 with 1 models keep loaded ... Current free memory is 4207.72 MB ... Unload model KModel Current free memory is 9210.89 MB ... Done.
Memory cleanup has taken 1.64 seconds
Total progress: 100%|██████████████████████████████████████████████████████████████████| 30/30 [00:32<00:00,  1.08s/it]
```

**Comment by BlafKing** [comment]
Thanks for reporting!
This issue has already been reported though, see: #342

Closed for duplicate report.
