### ISSUE TITLE
[BUG] Doesn't show multiple variations as [installed], only the latest.

### ISSUE THREAD

**Issue by gurukast** [BlafKing/sd-civitai-browser-plus#48]
When you have models with multiple variations, the extension doesn't let you know which are installed other than the latest. you have to click on each variation to see if you get a "download" or a "delete" to see if you already have it. 

Practical example - https://civitai.com/models/42903 Doll Likeness - by EDG
Creator has many variations, like Canadian Doll likeness, Polish Doll Likeness, and Dutch Girl Likenesss.
Browser plus will only show the "latest" one installed, and not all.

Even checkpoints that might have a  No VAE and an Inpainting model versions, will only show the "latest" one you have installed, vs all.

**Additional context**
* Extension version: 6232b9de | 2023-09-27 18:51:42 (v1.12.4)
* OS:Windows
A111 version: v1.6.0  •  python: 3.10.6  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.41.2 

[6232b9de](https://github.com/BlafKing/sd-civitai-browser-plus/commit/6232b9de956912d5a2ad2a3e2600a5409ed12b62)	2023-09-27 18:51:42

**Comment by BlafKing** [comment]
Thanks for letting me know!
I have a suspicion as to why this is happening, I'll publish a fix for it shortly! :)
