### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Autantpourmoi** [BlafKing/sd-civitai-browser-plus#52]
Hello, i"m able to browse civit ai site with the extension but can't download anything 

**To Reproduce**
1. Go to Civit AI tab
2. Click on 'Refresh'
3. select a model, VAE, Lora , whatever
4.Clik Download button 
5. see error 
6. Failed to start download: HTTPConnectionPool(host='localhost', port=6800): Max retries exceeded with url: /jsonrpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x2e97d02b0>: Failed to establish a new connection: [Errno 61] Connection refused'))
Error occured during download of "/Users/lucvaligny/stable-diffusion-webui/models/VAE/vaeFtMse840000Ema_v100.pt".

**Expected behavior**

**Screenshots**

**Additional context**
* Extension version: Version of this extension 10.0
* OS: Mac osx
* SD version: A1111 16.0
* Python: Python version in SD-WebUI 3.10.12
* Any Additional info

**Comment by BlafKing** [comment]
Have you tried the solution in known errors on the main page?

**Comment by BlafKing** [comment]
I'll close this thread since your issue should be solved by doing the steps mentioned above, if you still experience issues after doing so please feel free to send another message in this thread.

**Comment by Autantpourmoi** [comment]
Actually i have the last version , and still facing this pb

**Comment by BlafKing** [comment]
Ok, then you can try the other solution on the main pages under known issues.
Go to settings of webUI, go to civitai tab and disable downloading using Aria2.

**Comment by Autantpourmoi** [comment]
tried the manual installation , and it works, thanks
