### ISSUE TITLE
[Bug]: Models with an apostrophe in the title can't be loaded

### ISSUE THREAD

**Issue by ManOrMonster** [BlafKing/sd-civitai-browser-plus#66]
### Describe the bug.

Clicking on the card for a model with an apostrophe in the title does nothing. Will not try to load model info.

### Steps to reproduce the problem.

1. Search for LORAs using `'s` as the search term.
2. Click on any model card that appears.
3. Nothing.

### Expected behavior

Should load model info

### System info

* Extension version:
* OS:
* SD-WebUI version:
* Python:

### Console logs

```Shell
Nothing in auto1111 console

Chromium DevTools console shows this:
(index):1 Uncaught SyntaxError: missing ) after argument list (at (index):1:14)
```

**Comment by BlafKing** [comment]
Issue is now fixed by @SonyaHon!

I'll close this thread since it should now be resolved :)
