### ISSUE TITLE
[Bug]: Aria2 fails to download without --disable-ipv6

### ISSUE THREAD

**Issue by kloon15** [BlafKing/sd-civitai-browser-plus#70]
### Describe the bug.

Cant download with aria2 if --disable-ipv6 option is not supplied.

### Steps to reproduce the problem.

Local ipv6 but no external ipv6 support by isp.

### Expected behavior

Downloads the model.

### System info

Irrelevant, only specific to aria2.

### Console logs

```Shell
10/13 11:12:28 [ERROR] CUID#7 - Download aborted. URI=https://civitai.com/api/download/models/176425
Exception: [AbstractCommand.cc:312] errorCode=1 Network problem has occurred. cause:A socket operation was attempted to an unreachable network.
```

### Additional information

Please add a textfield in options to add command line options for aria2.

**Comment by BlafKing** [comment]
Sounds good!
That'll be easy to implement so I'll publish a hotfix for it in a few minutes 👍🏻

**Comment by BlafKing** [comment]
Latest commit adds a setting to add custom command flags for Aria2! :)

I'll close this thread since your issue should be resolved

**Comment by kloon15** [comment]
Thank you, that was quick!
