### ISSUE TITLE
[Bug]: TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by CoiNtusMaximus** [BlafKing/sd-civitai-browser-plus#71]
### Describe the bug.

Hi,
My A1111 produces an error when I try to pull updates from Civ:

 File "****\automatic1111\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 119, in contenttype_folder
    if "ADETAILER" in desc:
TypeError: argument of type 'NoneType' is not iterable

### Steps to reproduce the problem.

1. Go to .... 
2. Press ....
3. ...

### Expected behavior

Pulling updates from Civitai

### System info

* Extension version: v1.14.6
* OS: w11 64b
* SD-WebUI version: 1.6.0
* Python: python: 3.10.9

### Console logs

```Shell
File "****\automatic1111\stable-diffusion-webui\extensions\sd-civitai-browser-plus\scripts\civitai_api.py", line 119, in contenttype_folder
    if "ADETAILER" in desc:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by BlafKing** [comment]
Thx for the report! that should be an easy fix, I've published a hotfix which should fix this issue.

Please let me know if you're no longer experiencing the issue on the latest commit! :)

**Comment by BlafKing** [comment]
I'll close this thread since the error should be solved, feel free to send another message here if you're still experiencing the issue.
