### ISSUE TITLE
[Bug]: can't start webui with `--no-gradio-queue` enabled

### ISSUE THREAD

**Issue by cupangafk** [BlafKing/sd-civitai-browser-plus#77]
### Describe the bug.

ValueError: Progress tracking requires queuing to be enabled

log provided below

### Steps to reproduce the problem.

enable `--no-gradio-queue` when launching

### Expected behavior

webui run

### System info

* Extension version: 2b64e96c526837fcb6d8c815223aeb099224bc77
* OS:
```
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
* SD-WebUI version: https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/5ef669de080814067961f28357256e8fe27544f4
* Python:
```
Python 3.10.12
```

### Console logs

```Shell
Traceback (most recent call last):
  File "/root/sd/launch.py", line 48, in <module>
  File "/root/sd/launch.py", line 44, in main
  File "/root/sd/modules/launch_utils.py", line 436, in start
  File "/root/sd/webui.py", line 79, in webui
  File "/root/.venv/lib/python3.10/site-packages/gradio/blocks.py", line 1858, in launch
    self.validate_queue_settings()
  File "/root/.venv/lib/python3.10/site-packages/gradio/blocks.py", line 1690, in validate_queue_settings
    raise ValueError("Progress tracking requires queuing to be enabled.")
ValueError: Progress tracking requires queuing to be enabled.
```

### Additional information

when i uninstalled this extension, webui run just fine

**Comment by BlafKing** [comment]
Well, a fix for this is to not use the `--no-gradio-queue` command flag.
This extension relies on the queue system to show download progression, it won't work without it.

**Comment by cupangafk** [comment]
> May I ask what you need this flag for?

running on mobile broken when using gradio queue (webui has warning for that but i forgot what the messages)

run fine when without gradio queue

i can rely on the logs alone when it come to download progress, so for my use case i really don't need it to be shown on the webui

**Comment by BlafKing** [comment]
That's odd, SD-WebUI works fine for me on mobile without requiring `--no-gradio-queue` to be used.

I'll see if I can add a check that disables the download progress on the web page if `--no-gradio-queue` is used.

**Comment by cupangafk** [comment]
> That's odd, SD-WebUI works fine for me on mobile without requiring --no-gradio-queue to be used.

its an old phone, sorry bout that. 

maybe the chrome version in this phone is not supporting websocket yet eventhough the chrome version is already latest

**Comment by BlafKing** [comment]
The latest hotfix now disables progress tracking if the `--no-gradio-queue` command flag is used.

It currently does not automatically display the download progress in the terminal when the flag is used, I will try to add that in a future version, a workaround for now is enabling the Aria2 logs in the CivitAI settings tab :)

I'll close this issue since it should be resolved now! :)
