### ISSUE TITLE
[Bug]: Browser shows wrong model installed

### ISSUE THREAD

**Issue by Zaazu** [BlafKing/sd-civitai-browser-plus#81]
### Describe the bug.

When searching for a model already downloaded, it shows the wrong version installed.

![image](https://github.com/BlafKing/sd-civitai-browser-plus/assets/22891753/ad69169c-ab18-4380-b244-851e99a81f57)

### Steps to reproduce the problem.

1. Go to "Civit AI" tab
2. Search for a model already downloaded
3. Choose model version
4. Check to see if the correct model is listed as [Installed]

### Expected behavior

FenrisXL 14.5 should not be shown as installed, as that model has not been downloaded.

### System info

Extension version: 9047900
OS: Windows 11 Pro Version 22H2 (OS Build 22621.2428)
SD-WebUI version: v1.6.0 5ef669de080814067961f28357256e8fe27544f4
Python: 3.10.6

### Console logs

```Shell
venv "D:\Software\StableDiffusion\A1111\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Installing requirements for CivitAI Browser
Launching Web UI with arguments: --opt-sdp-no-mem-attention --no-half-vae --opt-channelslast --ckpt-dir ..\..\Models\Stable-diffusion --vae-dir ..\..\Models\VAE --lora-dir ..\..\Models\Lora --embeddings-dir ..\..\Models\Embeddings --esrgan-models-path ..\..\Models\ESRGAN --realesrgan-models-path ..\..\Models\RealESRGAN
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
Aria2 RPC started
2023-10-22 10:07:32,115 - ControlNet - INFO - ControlNet v1.1.411
ControlNet preprocessor location: D:\Software\StableDiffusion\A1111\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-10-22 10:07:32,235 - ControlNet - INFO - ControlNet v1.1.411
Loading weights [e247d28b0a] from ..\..\Models\Stable-diffusion\SDXL\fenrisxl_v1003Photorealistic.safetensors
Creating model from config: D:\Software\StableDiffusion\A1111\stable-diffusion-webui\repositories\generative-models\configs\inference\sd_xl_base.yaml
Applying attention optimization: sdp-no-mem... done.
Model loaded in 3.4s (load weights from disk: 0.8s, create model: 0.3s, apply weights to model: 2.0s, calculate empty prompt: 0.1s).
*Deforum ControlNet support: enabled*
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
[Lobe]: Initializing Lobe
Startup time: 28.1s (prepare environment: 11.4s, import torch: 2.8s, import gradio: 0.5s, setup paths: 1.4s, initialize shared: 0.2s, other imports: 1.0s, setup codeformer: 0.1s, load scripts: 6.4s, create ui: 4.2s, gradio launch: 0.2s).
```

**Comment by BlafKing** [comment]
The extension checks if a model is installed by looking for the matching SHA256 hash or a matching file name.

This issue is likely caused by another model having the SHA256 hash of FenrisXL14.5
This shouldn't be possible, since every file has a unique hash, but sometimes CivitAI assigns the wrong SHA256 hash to a model causing this to happen.

So you likely have another model with the hash of that version, causing it to display as installed.
Unfortunately there isn't much that I can do about this, since the issue is on CivitAI's end.
