### ISSUE TITLE
[Bug]: Checkpoints pretned to be downloaded fully, but its only a 100kb file

### ISSUE THREAD

**Issue by gurukast** [BlafKing/sd-civitai-browser-plus#86]
### Describe the bug.

so far happens with these two. even deleting them both through the browser and directly with file manager, same thing happens.
It downloads in one second, says complete, but it didn't actually download at all. Shows the lovely green border as if it is.
 Only happens with the latest release listed in the drop-down
Protovision XL
https://civitai.com/models/125703
Nightvision XL
https://civitai.com/models/128607

Not sure if civitai error, or extensions

### Steps to reproduce the problem.

Click on any of the checkpoints.
chose latest version
click download.
Download completes in 1 second, now says "installed"
Refreshing page still shows like its fully installed

### Expected behavior

Download the actual checkpoint

### System info

v1.14.6
Windows 10
version: [v1.6.0]  •  python: 3.10.6  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.41.2  • 

### Console logs

```Shell
*** Download Progress Summary as of Sat Oct 28 08:13:05 2023 ***
======================================================================================================================
[#e81793 0B/0B CN:1 DL:0B]
FILE: M:/AI/A160/stable-diffusion-webui/models/Stable-diffusion/SDXL/protovisionXLHighFidelity3D_release0630Bakedvae.safetensors
----------------------------------------------------------------------------------------------------------------------

[#e81793 0B/0B CN:1 DL:0B]
10/28 08:13:05 [NOTICE] CUID#71907 - Redirecting to https://civitai.com/login?returnUrl=%2Fmodels%2F125703&reason=download-auth

10/28 08:13:06 [NOTICE] Download complete: M:/AI/A160/stable-diffusion-webui/models/Stable-diffusion/SDXL/protovisionXLHighFidelity3D_release0630Bakedvae.safetensors
Model saved to: M:\AI\A160\stable-diffusion-webui\models\Stable-diffusion\SDXL\protovisionXLHighFidelity3D_release0630Bakedvae.safetensors
Preview image saved to: M:\AI\A160\stable-diffusion-webui\models\Stable-diffusion\SDXL\protovisionXLHighFidelity3D_release0630Bakedvae.preview.png
```

**Comment by ManOrMonster** [comment]
I'm experiencing the same issue with LORAs.

**Comment by Terroosh** [comment]
If you click on the model download link it says "The creator of this asset requires you to be logged in to download it"
This may be why it fails to download.

https://civitai.com/api/download/models/201643

**Comment by ManOrMonster** [comment]
Looks like this is the reason.

Poorly done, Civitai. This makes it impossible to download a model via API if the uploader chose that option, unless there's a way to pass in credentials to it.

**Comment by BlafKing** [comment]
Thx for figuring out the cause @Terroosh!

I'll look into the possibility of providing credentials to a download.

**Comment by AbsolomTDaak** [comment]
I had the same problem for the past few days, i fixed it by going into settings and unchecking
Download models using Aria2 (Disable to use the old download method)
and now it seems to be downloading the stuff i choose okay (touch wood), so maybe it has something to do with Aria2.
Just my thoughts mind you.

**Comment by BlafKing** [comment]
Disabling Aria2 doesn't fix being able to download models where it is required to be logged in.
the models that the original post mentioned for example: [Protovision XL](https://civitai.com/models/125703), [Nightvision XL](https://civitai.com/models/128607)

I've found a fix for it however which I will publish soon which works on both old download method and Aria2! :)

**Comment by BlafKing** [comment]
Latest version ([v1.14.7](https://github.com/BlafKing/sd-civitai-browser-plus/commit/3759cbd4441212a8d747f0e3202bff1b9eb562e7)) should now properly download any models that require the user to be logged in.

I've made a placeholder account of which I'm using the API Key of for downloads.
afaik this should work well, but please do let me know if it ever breaks in the future! :) 
(maybe CivitAI doesn't like it when a single API Key gets used for a lot of downloads)
