### ISSUE TITLE
[BUG] "Filter Base Model" mixed with large amounts of models is confusing

### ISSUE THREAD

**Issue by ManOrMonster** [BlafKing/sd-civitai-browser-plus#9]
**Describe the bug**
When searching (especially through a larger time period) and choosing SDXL 1.0 for "Filter Base Model", the display is confusing, because there will be pages and pages of hidden thumbnails.

**To Reproduce**
1. Go to Content Type: "LORA", Time Period: "All Time", Sort by "Highest Rated"
2. Optional: "Divide cards by date"
3. Click Refresh
4. Blank pages or many dividers with no thumbnails

**Expected behavior**
Thumbnails should appear. I know the filter hides thumbnails due to the API not being able to return only specified base models.

I don't know what you could do to fix this, but you could dim/make transparent those thumbnails that don't match the model filter. That way there's not blank pages where thumbnails would be expected to be, and it would make it more obvious that the filter is merely hiding these in the display. See my second screenshot below, where I set SD 1.5 models to only display at 10% opacity. (Side note: you can see the NSFW blur is not too effective at tile size 12 😐).

**Screenshot**
Issue:
<img width="1346" alt="image" src="https://github.com/BlafKing/sd-civitai-browser-plus/assets/3925151/28dad945-9004-4095-91d9-0f8e683d6209">

Proposed update:
<img width="883" alt="image" src="https://github.com/BlafKing/sd-civitai-browser-plus/assets/3925151/c547cfd4-c753-4a3f-9750-6b50eec3bb11">

**Comment by BlafKing** [comment]
Dimming the cards seems like a good solution to me, and I haven't thought about the blur needing to increase if the tile size increases lol, good catch.

This is a very easy fix/adjustment so I'll upload an updated version in a bit, thanks for the request! 👍🏻
